import json, os
os.makedirs('/workspace/public/data', exist_ok=True)

V = []

def w(word, meaning, example, category):
    V.append({"word": word, "meaning": meaning, "example": example, "category": category})

# 高频 120
for word, m, e in [
    ("abandon","v. 放弃；抛弃","Many students abandon healthy habits when exams approach."),
    ("ability","n. 能力；才能","The ability to communicate effectively is crucial."),
    ("academic","adj. 学术的","Academic research requires rigorous methodology."),
    ("accelerate","v. 加速；促进","Technology accelerates the pace of change."),
    ("access","n./v. 访问；使用权","Everyone should have equal access to education."),
    ("accommodate","v. 容纳；适应","Universities accommodate international students."),
    ("accomplish","v. 完成；实现","She accomplished her goal through effort."),
    ("accurate","adj. 准确的；精确的","Accurate data is essential for research."),
    ("achieve","v. 实现；达到","Students achieve success through disciplined study."),
    ("acknowledge","v. 承认；确认","Researchers acknowledge study limitations."),
    ("acquire","v. 获得；习得","Children acquire language through interaction."),
    ("adequate","adj. 足够的","Adequate sleep is vital for good health."),
    ("adhere","v. 坚持；遵守","Students must adhere to examination regulations."),
    ("advocate","v./n. 提倡；拥护者","Educators advocate student-centered learning."),
    ("affect","v. 影响；感动","Social media affects how people communicate."),
    ("aggregate","n./v. 总计；聚合","Aggregate data shows trends in online learning."),
    ("alleviate","v. 减轻；缓解","Exercise alleviates symptoms of stress."),
    ("allocate","v. 分配；分派","Governments allocate resources efficiently."),
    ("alternative","n./adj. 替代物；可选的","Renewables provide an alternative to fossil fuels."),
    ("ambiguous","adj. 模棱两可的","Ambiguous instructions lead to misunderstanding."),
    ("ambitious","adj. 有雄心的","Ambitious students set challenging goals."),
    ("analyze","v. 分析；解析","Researchers analyze complex data sets."),
    ("approach","n./v. 方法；接近","A balanced approach yields best results."),
    ("appropriate","adj. 适当的","Appropriate vocabulary is essential in writing."),
    ("arbitrary","adj. 任意的","Arbitrary decisions undermine trust in leadership."),
    ("articulate","v./adj. 清晰表达","Effective speakers articulate ideas clearly."),
    ("assess","v. 评估；评价","Teachers assess student progress regularly."),
    ("assume","v. 假定；承担","One cannot assume all students learn alike."),
    ("attain","v. 达到；获得","It takes years to attain language proficiency."),
    ("authority","n. 权威；当局","Authorities must address student well-being."),
    ("available","adj. 可利用的","Online resources support independent learning."),
    ("beneficial","adj. 有益的","Reading is beneficial for vocabulary."),
    ("bias","n./v. 偏见","Researchers should avoid personal bias."),
    ("capability","n. 能力；性能","Technology enhances human capability."),
    ("capacity","n. 容量；能力","The brain has extraordinary learning capacity."),
    ("category","n. 种类；类别","Students organize notes into clear categories."),
    ("cease","v. 停止；终止","Traditional industries have ceased to exist."),
    ("challenge","n./v. 挑战","Learning a language presents challenges."),
    ("channel","n./v. 渠道；引导","Social media is a major information channel."),
    ("circumstance","n. 情况；境况","Under no circumstances should students plagiarize."),
    ("cite","v. 引用；引证","Researchers cite sources in literature reviews."),
    ("clarify","v. 澄清；阐明","The professor clarified the complex theory."),
    ("coherent","adj. 连贯的","A coherent argument requires logic and evidence."),
    ("coincide","v. 一致；同时发生","Rise in obesity coincides with fast food popularity."),
    ("collaborate","v. 合作；协作","Students collaborate on group projects."),
    ("commence","v. 开始；着手","The conference commences with a keynote."),
    ("commodity","n. 商品；日用品","Clean water is a valuable commodity."),
    ("comparable","adj. 可比较的","Online courses are comparable to traditional."),
    ("compatible","adj. 兼容的","Software is compatible with most systems."),
    ("compel","v. 强迫； compelling 令人信服的","Economic hardship compels families to relocate."),
    ("compensate","v. 补偿；赔偿","Nothing compensates for lost education."),
    ("competent","adj. 有能力的","Competent teachers inspire confidence."),
    ("compile","v. 汇编；编写","She compiled research for her dissertation."),
    ("complement","n./v. 补充；补足","Theory and practice complement each other."),
    ("comply","v. 遵守；顺从","Students must comply with the code of conduct."),
    ("comprehensive","adj. 全面的；综合的","A comprehensive review strengthens papers."),
    ("concept","n. 概念；观念","Sustainable development is a global concept."),
    ("conclude","v. 得出结论","Researchers conclude early intervention works best."),
    ("conduct","v./n. 进行；行为","Scientists conduct experiments to test hypotheses."),
    ("confer","v. 授予；协商","The university confers degrees on graduates."),
    ("confine","v./n. 限制；界限","Learning should not be confined to classrooms."),
    ("confirm","v. 确认；证实","Studies confirmed the initial findings."),
    ("conflict","n./v. 冲突；矛盾","Work and study often conflict for adults."),
    ("conform","v. 遵守；符合","Teenagers conform to peer pressure."),
    ("consensus","n. 一致；共识","There is consensus climate action is needed."),
    ("consequence","n. 结果；后果","Poor diet has serious health consequences."),
    ("considerable","adj. 相当大的","Considerable progress has been made."),
    ("constitute","v. 构成；组成","Women constitute the majority of students."),
    ("constrain","v. 约束；限制","Financial constraints limit access to education."),
    ("construct","v. 建造；构建","Students construct logical arguments in essays."),
    ("consult","v. 咨询；商议","Patients consult medical professionals."),
    ("consume","v. 消耗；消费","Modern lifestyles consume vast resources."),
    ("contemporary","adj. 当代的","Contemporary art reflects modern society."),
    ("contradict","v. 反驳；矛盾","His actions contradict his principles."),
    ("contrary","adj. 相反的","Contrary to belief, introverts can lead well."),
    ("contribute","v. 贡献；捐献","Individuals contribute to environmental protection."),
    ("controversial","adj. 有争议的","Genetic engineering is controversial."),
    ("conventional","adj. 传统的","Conventional teaching faces digital challenges."),
    ("convey","v. 传达；表达","Art conveys emotions words cannot."),
    ("cooperate","v. 合作；配合","Countries must cooperate on global issues."),
    ("coordinate","v. 协调；整合","Leaders coordinate team efforts."),
    ("core","n./adj. 核心；核心的","Critical thinking is a core skill."),
    ("correlate","v. 关联；使相关","Studies correlate sleep with performance."),
    ("correspond","v. 符合；对应","Outcomes correspond to student engagement."),
    ("credible","adj. 可信的；可靠的","Credible research needs transparency."),
    ("critical","adj. 关键的；批判的","Early education plays a critical role."),
    ("crucial","adj. 关键的；决定性的","Vocabulary is crucial for learners."),
    ("cultivate","v. 培养；耕作","Parents cultivate reading habits in children."),
    ("cumbersome","adj. 笨重的；累赘的","Paper systems are increasingly cumbersome."),
    ("curriculum","n. 课程；全部课程","Curriculum balances academic and practical skills."),
    ("decline","v./n. 下降；衰退","There is a decline in traditional bookstores."),
    ("dedicate","v. 致力；奉献","She dedicated herself to environmental science."),
    ("deduce","v. 推断；演绎","Researchers deduced a significant correlation."),
    ("defect","n./v. 缺陷；缺点","Genetic defects cause health conditions."),
    ("define","v. 定义；规定","Define key terms at the start of an essay."),
    ("deliberate","adj./v. 故意的；深思熟虑的","Language learning requires deliberate practice."),
    ("demonstrate","v. 证明；演示","Graphs demonstrate increase in temperatures."),
    ("denote","v. 表示；指示","Certain phrases denote a shift in argument."),
    ("depict","v. 描述；描绘","The chart depicts population changes."),
    ("derive","v. 得到；源于","Many English words derive from Latin."),
    ("design","n./v. 设计；计划","Teachers design lessons for engagement."),
    ("designate","v. 指定；指派","Areas designated as wildlife reserves."),
    ("despise","v. 鄙视；厌恶","He despised dishonesty in academic work."),
    ("detect","v. 察觉；发现","Early screening detects diseases."),
    ("determine","v. 决定；确定","Many factors determine language success."),
    ("detrimental","adj. 有害的","Excessive screen time is detrimental."),
    ("develop","v. 发展；开发","Universities develop industry partnerships."),
    ("devise","v. 设计；发明","Researchers devised a new analysis method."),
    ("diagnose","v. 诊断；判断","Doctors diagnose illnesses based on tests."),
    ("diminish","v. 减少；削弱","Traditional values have diminished."),
    ("discipline","n./v. 纪律；学科","Self-discipline is essential for goals."),
    ("disclose","v. 透露；公开","Companies disclose financial information."),
    ("discrete","adj. 离散的；分立的","Course breaks topics into discrete modules."),
    ("discriminate","v. 歧视；区别","Laws prohibit employment discrimination."),
    ("dismiss","v. 解散；不予考虑","Do not dismiss alternative perspectives."),
    ("disorder","n. 混乱；失调；疾病","Sleep disorders affect performance."),
    ("disperse","v. 驱散；散开","The crowd dispersed when police arrived."),
    ("displace","v. 取代；迫使离开","Automation may displace workers."),
    ("display","n./v. 显示；展览","The museum displays ancient artifacts."),
    ("dispose","v. 处理；处置","Cities must dispose of waste sustainably."),
    ("distinct","adj. 明显的；独特的","Each discipline has distinct methodology."),
    ("distribute","v. 分配；散布","Governments distribute vaccines equitably."),
    ("diverge","v. 分歧；偏离","Opinions diverge on nuclear energy."),
    ("dominate","v. 支配；控制","A few corporations dominate the tech industry."),
    ("dramatic","adj. 戏剧性的；急剧的","There have been dramatic changes in technology."),
    ("drastic","adj. 激烈的；极端的","Drastic measures may reverse environmental damage."),
    ("duplicate","adj./v./n. 复制；副本","Students must not submit duplicate work."),
    ("dynamic","adj. 动态的；有活力的","Cities are dynamic centers of innovation.")]:
    w(word, m, e, "高频")

hi_freq = len(V)
print(f"高频: {hi_freq}")

# 学术 80
academic_list = [
    ("economy","n. 经济","A stable economy provides employment opportunities."),
    ("eliminate","v. 消除；排除","The goal is to eliminate preventable diseases."),
    ("emerge","v. 出现；兴起","New technologies emerge continuously."),
    ("emphasize","v. 强调；着重","Educators emphasize critical thinking."),
    ("encounter","v./n. 遭遇；遇到","Students encounter difficulties at university."),
    ("enforce","v. 实施；执行","Schools enforce safety policies."),
    ("enhance","v. 提高；增强","Software enhances language learning."),
    ("enormous","adj. 巨大的","Growth of online learning has been enormous."),
    ("ensure","v. 保证；确保","Governments must ensure equal access."),
    ("entail","v. 需要；牵涉","Research entails attention to detail."),
    ("entity","n. 实体","University operates as independent entity."),
    ("environment","n. 环境","Protecting environment requires global action."),
    ("equivalent","adj./n. 等价的；等价物","Diploma not equivalent to competence."),
    ("evolve","v. 进化；演变","Languages evolve through cultural contact."),
    ("exaggerate","v. 夸大；夸张","Media sometimes exaggerates technology risks."),
    ("exceed","v. 超过；胜过","Project exceeded budget by 30 percent."),
    ("exclude","v. 排除；不包括","No student excluded due to finance."),
    ("execute","v. 执行；实施","Planning is one thing, executing another."),
    ("exempt","adj./v. 被免除；豁免","Charities exempt from taxation."),
    ("exhaust","n./v. 耗尽；废气","Vehicle exhaust causes urban pollution."),
    ("exhibit","v./n. 显示；展出","Successful learners exhibit curiosity."),
    ("expand","v. 扩大；扩展","Universities expand online offerings."),
    ("explicit","adj. 明确的；清楚的","Assignment instructions should be explicit."),
    ("exploit","v. 利用；开发","Nations must exploit resources responsibly."),
    ("explore","v. 探索；探究","Students explore diverse disciplines."),
    ("extend","v. 延伸；延长","Government extended consultation deadline."),
    ("external","adj. 外部的；外来的","Balance internal motivation with external pressure."),
    ("extract","v./n. 提取；摘录","Researchers extract patterns from data."),
    ("facilitate","v. 促进；使容易","Technology facilitates distance communication."),
    ("factor","n./v. 因素；要素","Economic factors influence policy decisions."),
    ("faculty","n. 全体教员；学院","University attracts international faculty."),
    ("feasible","adj. 可行的","Renewables economically feasible now."),
    ("feature","n./v. 特征；以...为特色","Curriculum features digital literacy courses."),
    ("figure","n./v. 数字；人物","Figures indicate rising youth unemployment."),
    ("finance","n./v. 财政；金融","Students work to finance education."),
    ("fluctuate","v. 波动；起伏","Oil prices fluctuate with conditions."),
    ("focus","v./n. 集中；焦点","Report focuses on urbanization impacts."),
    ("format","n./v. 格式；设计","Essays follow academic format guidelines."),
    ("formulate","v. 制定；规划","Researchers formulate hypotheses first."),
    ("foundation","n. 基础；基金会","Early education lays lifelong foundation."),
    ("fraction","n. 分数；部分","Only fraction of applicants are admitted."),
    ("fragment","n./v. 碎片；使分裂","Digital media presents fragmented info."),
    ("framework","n. 框架；体系","Study proposes framework for cultural change."),
    ("fulfill","v. 履行；实现","Education helps fulfill personal potential."),
    ("function","n./v. 功能；运行","Libraries function as community centers."),
    ("fundamental","adj./n. 基本的；根本的","Freedom is a fundamental human right."),
    ("generate","v. 产生；生成","Wind turbines generate electricity cleanly."),
    ("genuine","adj. 真正的；真诚的","Genuine curiosity drives meaningful research."),
    ("global","adj. 全球的","Climate change is a global challenge."),
    ("govern","v. 统治；管理","Principles govern ethical research practices."),
    ("gradual","adj. 逐渐的","Proficiency develops through gradual effort."),
    ("guarantee","v./n. 保证；担保","Degree does not guarantee employment."),
    ("hence","adv. 因此；所以","Demand rising; hence training is critical."),
    ("hierarchy","n. 等级制度","Universities have complex hierarchies."),
    ("highlight","v./n. 强调；突出","Study highlights educational disparities."),
    ("hypothesis","n. 假设；假说","Researchers test hypotheses via experiments."),
    ("identical","adj. 同一的","No two learning experiences are identical."),
    ("identify","v. 识别；确定","Teachers identify individual learning needs."),
    ("ideology","n. 意识形态","Ideologies shape welfare approaches."),
    ("ignore","v. 忽视；不理","Cannot ignore long-term environmental costs."),
    ("illustrate","v. 说明；阐明","Statistics illustrate housing problem scale."),
    ("immense","adj. 巨大的","Internet contains immense information."),
    ("impact","n./v. 影响；冲击","Automation impacts future of work."),
    ("implement","v./n. 执行；实施","Governments implement climate policies."),
    ("implication","n. 含义；影响","Findings have important policy implications."),
    ("impose","v. 强加；征收","Authorities impose safety restrictions."),
    ("incentive","n. 激励；动机","Financial incentives reduce pollution."),
    ("incident","n. 事件","Safety incidents have serious consequences."),
    ("indicate","v. 表明；指出","Research indicates exercise benefits cognition."),
    ("individual","n./adj. 个人；个体","Each individual learns differently."),
    ("induce","v. 引起；导致","Stress induces physical symptoms."),
    ("inevitable","adj. 不可避免的","Change is inevitable in development."),
    ("influence","n./v. 影响；作用","Family influences educational outcomes."),
    ("inherent","adj. 固有的；内在的","Language has inherent complexity."),
    ("initiate","v. 开始；创始","Governments initiate support programs."),
    ("innovate","v. 创新；改革","Companies innovate for competitiveness."),
    ("insight","n. 洞察力","Study provides insight into child development."),
    ("inspect","v. 检查；审查","Officials inspect facilities regularly."),
    ("inspire","v. 激发；鼓舞","Great teachers inspire beyond textbooks."),
    ("install","v. 安装；设置","Schools install security cameras."),
    ("institute","n./v. 学会；学院；建立","Institute conducts sustainability research."),
    ("integrity","n. 正直；完整性","Academic integrity is foundational."),
    ("intense","adj. 强烈的；紧张的","Intense study needs rest periods."),
    ("interpret","v. 解释；说明","Researchers interpret data in context."),
    ("intervene","v. 干预；介入","Early intervention helps learning difficulties."),
    ("intimate","adj./v. 亲密的；私人的","Students need intimate grammar knowledge."),
    ("intrinsic","adj. 固有的；本质的","Education has intrinsic value beyond jobs.")]

for a, b, c in academic_list:
    w(a, b, c, "学术")
print(f"学术: {len(V)}")

# 写作 80
writing_list = [
    ("objective","n./adj. 目标；客观的","Writing requires objective approach."),
    ("observe","v. 观察；注意到","Researchers observe behavior patterns."),
    ("obvious","adj. 明显的","Technology transformed communication obviously."),
    ("occasion","n./v. 时机；场合","Students occasionally need extra support."),
    ("occur","v. 发生；出现","Similar problems occur in developing countries."),
    ("odd","adj. 奇怪的；奇数的","Data showed odd patterns needing review."),
    ("offset","v./n. 抵消；补偿","Renewables offset traditional emissions."),
    ("ongoing","adj. 进行中的","Climate change is an ongoing threat."),
    ("operate","v. 运转；操作","Governments operate within legal boundaries."),
    ("optimal","adj. 最佳的","Optimal learning needs rest and nutrition."),
    ("optimum","n./adj. 最佳效果","Optimum temperature varies per person."),
    ("option","n. 选项；选择权","Students given options for demonstrating knowledge."),
    ("organize","v. 组织；整理","Writers organize ideas logically for clarity."),
    ("orient","v. 使适应；确定方向","Education orients toward lifelong learning."),
    ("outcome","n. 结果；成果","Educational outcomes depend on many factors."),
    ("overlook","v./n. 俯瞰；忽视","Policymakers overlook social health determinants."),
    ("overall","adj./adv. 总体的","Overall, education benefits outweigh costs."),
    ("overwhelming","adj. 压倒性的","Overwhelming majority values teacher feedback."),
    ("pace","n./v. 步速；节奏","Fast pace of life affects well-being."),
    ("panel","n./v. 面板；专门小组","Expert panel reviewed methodology."),
    ("paradigm","n. 范例；范式","Digital tech is paradigm shift in education."),
    ("paradox","n. 悖论；矛盾","Paradox: connectivity leads to loneliness."),
    ("parallel","adj./n./v. 平行的；对比","Parallels exist between language and music."),
    ("participate","v. 参与；参加","Active participants learn more effectively."),
    ("passive","adj./n. 被动的；消极的","Passive learning alone is insufficient."),
    ("perceive","v. 察觉；感知","People perceive information differently."),
    ("permanent","adj. 永久的","Education has permanent effects on society."),
    ("persist","v. 坚持；持续","Challenges persist despite tech improvements."),
    ("phenomenon","n. 现象","Globalization is complex phenomenon."),
    ("philosophy","n. 哲学；人生观","Each system reflects learning philosophy."),
    ("physical","adj./n. 身体的；物理的","Physical activity boosts cognition."),
    ("pivotal","adj. 关键的","University years are pivotal for careers."),
    ("policy","n. 政策；方针","Governments formulate policy from research."),
    ("portray","v. 描绘；扮演","Media portrays scientists stereotypically."),
    ("potential","adj./n. 潜在的；潜力","Every child has developable potential."),
    ("practical","adj. 实际的；实用的","Practical skills complement theory at work."),
    ("precise","adj. 精确的","Precise language essential in academic writing."),
    ("predict","v. 预言；预测","Economists predict renewable energy growth."),
    ("predominant","adj. 主要的","English is predominant global language."),
    ("prefer","v. 更喜欢；宁愿","Most prefer interactive over passive learning."),
    ("premise","n./v. 前提；假设","Argument based on equality premise."),
    ("prepare","v. 准备；预备","Universities prepare students for careers."),
    ("prescribe","v. 开处方；规定","Doctors prescribe medication and lifestyle."),
    ("present","adj./v./n. 现在的；呈现","Students present findings at seminars."),
    ("preserve","v./n. 保护；保持","Institutions preserve cultural heritage."),
    ("primary","adj. 主要的；初级的","Primary purpose is developing critical thought."),
    ("principle","n. 原则；准则","Ethical principles guide research conduct."),
    ("priority","n. 优先；优先权","Reducing dropout rates must be priority."),
    ("proceed","v. 进行；继续","Students proceed through materials systematically."),
    ("process","n./v. 过程；加工","Learning is active engagement process."),
    ("procure","v. 获得；取得","Libraries procure research resources."),
    ("produce","v./n. 生产；制作","Universities produce innovation-driving research."),
    ("professional","adj./n. 专业的","Professional development improves teaching."),
    ("proficient","adj. 熟练的；精通的","Proficient language needs years practice."),
    ("profile","n./v. 形象；轮廓","Institution maintains high academic profile."),
    ("profound","adj. 深刻的；深远的","Education has profound life impact."),
    ("progress","n./v. 进步；进展","Students track progress for self-improvement."),
    ("project","n./v. 项目；规划","Project investigates literacy improvement methods."),
    ("promote","v. 促进；提升","Schools promote respect and responsibility."),
    ("prompt","adj./v. 迅速的；提示","Teachers provide prompt assignment feedback."),
    ("prone","adj. 有...倾向的","Stressed students prone to careless errors."),
    ("proper","adj. 适当的；恰当的","Proper citation prevents academic plagiarism."),
    ("proportion","n./v. 比例；部分","Small proportion achieve highest grades."),
    ("propose","v. 提议；建议","Paper proposes academic improvement strategies."),
    ("prospective","adj. 预期的；未来的","Prospective international students face challenges."),
    ("protocol","n. 协议；议定书","Researchers follow ethical protocols."),
    ("provide","v. 提供；供应","Education provides growth opportunities."),
    ("provision","n. 规定；供应","Scholarship provision enables higher education."),
    ("psychological","adj. 心理的","Psychological factors influence motivation."),
    ("pursue","v. 追求；从事","Many pursue postgraduate study for careers."),
    ("qualitative","adj. 定性的","Qualitative research explores subjective experience."),
    ("quantify","v. 量化","Difficult to quantify long-term education benefit."),
    ("query","n./v. 查询；疑问","Students query assumptions critically."),
    ("question","n./v. 问题；怀疑","Researchers question conventional wisdom.")]

for a, b, c in writing_list:
    w(a, b, c, "写作")
print(f"写作: {len(V)}")

# 口语 50
speaking_list = [
    ("random","adj./n. 随机的；任意的","Random vocabulary study less effective."),
    ("range","n./v. 范围；幅度","Abilities range from beginner to advanced."),
    ("rational","adj. 合理的；理性的","Rational decisions consider evidence."),
    ("react","v. 反应","People react differently to exam stress."),
    ("readily","adv. 容易地；乐意地","Information readily available digitally."),
    ("reality","n. 现实；真实","Reality: learning requires sustained effort."),
    ("realm","n. 领域；王国","AI advances into new application realms."),
    ("reason","n./v. 理由；推理","Many reasons exist to study abroad."),
    ("recall","v./n. 回忆；回想","Spaced repetition improves recall ability."),
    ("recent","adj. 最近的","Recent developments transformed education."),
    ("recipe","n. 食谱；秘诀","Hard work is recipe for success."),
    ("recognize","v. 承认；认出","Teachers recognize individual strengths."),
    ("recommend","v. 推荐；劝告","Experts recommend daily language practice."),
    ("reconcile","v. 调和；使一致","Challenging to reconcile work and family."),
    ("record","v./n. 记录；唱片","Students record lectures for later review."),
    ("recover","v. 恢复；痊愈","Need time to recover after exams."),
    ("recruit","v./n. 招募；招聘","Universities recruit international students."),
    ("reduce","v. 减少；降低","Universities reduce barriers for students."),
    ("refer","v. 提到；参考","Scholars refer to foundational theories."),
    ("reflect","v. 反射；反省","Students reflect on feedback to improve."),
    ("reform","n./v. 改革；改良","Educational reform improves outcomes."),
    ("regard","v./n. 认为；尊敬","People regard education as success key."),
    ("regime","n. 政权；制度","Different regimes prioritize education differently."),
    ("region","n. 地区；区域","Regional variations exist in education quality."),
    ("register","v./n. 注册；登记","Students register for courses online."),
    ("regulate","v. 管理；规定","Governments regulate education standards."),
    ("reject","v. 拒绝；驳回","Peer review may reject flawed papers."),
    ("relate","v. 联系；叙述","Students relate theory to practical application."),
    ("relax","v. 放松；休息","Students need time to relax and recharge."),
    ("release","v./n. 释放；发布","New technology releases regularly."),
    ("relevant","adj. 相关的；有关的","Material must be relevant to student goals."),
    ("relieve","v. 减轻；解除","Holidays relieve academic pressure."),
    ("remain","v. 保持；剩下","Challenges remain despite improvements."),
    ("remark","n./v. 评论；注意到","Students remarked on course quality."),
    ("remedy","n./v. 补救；治疗","Remedy exists for learning difficulties."),
    ("render","v. 致使；给予","Technology renders certain skills obsolete."),
    ("renew","v. 更新；恢复","Students renew library books online."),
    ("renowned","adj. 著名的；有名的","Renowned professors teach at the university."),
    ("replace","v. 取代；更换","Digital tools may not replace teachers."),
    ("replicate","v. 复制；重复","Research should be replicable by others."),
    ("represent","v. 代表；表现","Data represents population characteristics."),
    ("require","v. 需要；要求","Courses require consistent study effort."),
    ("reserve","v./n. 保留；储备","Reserve time each day for reading."),
    ("reside","v. 居住；属于","Most students reside in campus housing."),
    ("resolve","v. 解决；决心","Students resolve to improve their grades."),
    ("resort","n./v. 胜地；求助于","Some resort to plagiarism when desperate."),
    ("resource","n./v. 资源；物力","Digital resources supplement textbooks."),
    ("respond","v. 回答；响应","Students respond positively to encouragement."),
    ("restore","v. 恢复；修复","Efforts restore damaged historical buildings."),
    ("restrict","v. 限制；约束","Some universities restrict internet access.")]

for a, b, c in speaking_list:
    w(a, b, c, "口语")
print(f"口语: {len(V)}")

# 阅读 50
reading_list = [
    ("retain","v. 保持；保留","Readers retain information better with notes."),
    ("retire","v. 退休；退隐","Many professors retire after long careers."),
    ("retrieve","v. 检索；恢复","Students retrieve articles from databases."),
    ("reveal","v. 显示；透露","Research reveals patterns in reading behavior."),
    ("revenue","n. 收入；税收","Universities seek alternative revenue sources."),
    ("reverse","v./n. 颠倒；相反","Reversing climate trends requires action."),
    ("review","n./v. 复习；评论","Literature review synthesizes prior research."),
    ("revise","v. 修改；修订","Students revise essays based on feedback."),
    ("revolution","n. 革命；旋转","Digital revolution transformed publishing."),
    ("rigorous","adj. 严格的；严厉的","Academic research requires rigorous method."),
    ("risk","n./v. 风险；冒险","Plagiarism risks severe consequences."),
    ("robust","adj. 强健的；稳健的","Robust argument withstands counterpoints."),
    ("role","n. 角色；作用","Libraries continue important educational role."),
    ("route","n./v. 路线；路径","Students choose different career routes."),
    ("rural","adj. 农村的；乡村的","Rural students face access challenges."),
    ("safeguard","v./n. 保护；保障","Systems safeguard personal data privacy."),
    ("sample","n./v. 样本；抽样","Researchers sample population for surveys."),
    ("satisfy","v. 满足；使满意","Satisfy assignment requirements carefully."),
    ("scenario","n. 方案；情景","Consider worst-case scenario in planning."),
    ("schedule","n./v. 时间表；安排","Students schedule study time weekly."),
    ("scheme","n./v. 计划；方案","Government schemes support student housing."),
    ("scholar","n. 学者；奖学金获得者","Distinguished scholars publish widely."),
    ("scientific","adj. 科学的","Scientific method advances human knowledge."),
    ("scope","n./v. 范围；领域","Course scope covers broad historical range."),
    ("screen","n./v. 屏幕；筛选","Universities screen applicants carefully."),
    ("section","n./v. 部分；部门","Reading sections test comprehension skill."),
    ("sector","n./v. 部门；行业","Education sector needs greater investment."),
    ("secure","adj./v. 安全的；获得","Secure documents and data appropriately."),
    ("seek","v. 寻求；寻找","Students seek knowledge beyond requirements."),
    ("segment","n./v. 段；部分","Market segment analysis reveals trends."),
    ("select","v./adj. 选择；精选","Select appropriate evidence for arguments."),
    ("senior","adj./n. 高级的；年长的","Senior students mentor first-years."),
    ("sense","n./v. 感觉；意义","Reading comprehension makes sense of text."),
    ("separate","adj./v. 分离的；分开","Separate main ideas from supporting details."),
    ("sequence","n./v. 顺序；序列","Events follow predictable chronological sequence."),
    ("series","n. 系列；连续","Read the entire series for full understanding."),
    ("severe","adj. 严重的；严厉的","Severe penalties apply for academic fraud."),
    ("shift","n./v. 移动；变化","Cultural shift toward digital reading."),
    ("significant","adj. 重要的；显著的","Text contains significant historical details."),
    ("similar","adj. 相似的","Themes similar across different authors."),
    ("simulate","v. 模拟；模仿","Software simulates real reading conditions."),
    ("site","n./v. 位置；地点","Cite the original source site accurately."),
    ("situation","n. 情况；形势","Describe situation in the passage context."),
    ("sizable","adj. 相当大的","Sizable portion of text describes methodology."),
    ("skill","n./v. 技能；技巧","Reading skills improve with deliberate practice."),
    ("social","adj. 社会的","Social context influences reading interpretation."),
    ("sole","adj./n. 唯一的；鞋底","Sole author credited in the paper."),
    ("solution","n. 溶液；解决方案","Reading practice is solution to slow speed."),
    ("solve","v. 解决；解答","Read carefully to solve comprehension questions."),
    ("somewhat","adv. 稍微；有点","Author somewhat biased in the conclusion.")]

for a, b, c in reading_list:
    w(a, b, c, "阅读")
print(f"阅读: {len(V)}")

# 听力 40
listening_list = [
    ("source","n./v. 来源；出处","Identify information source in the lecture."),
    ("specific","adj. 具体的；特定的","Listen for specific details in conversation."),
    ("specify","v. 指定；详细说明","Professor specified chapter for next week."),
    ("spectrum","n. 光谱；范围","Broad spectrum of opinions expressed."),
    ("sphere","n. 球体；范围","Public sphere discussion of the issue."),
    ("stable","adj./n. 稳定的","Stable learning environment supports growth."),
    ("standard","n./adj. 标准；标准的","Meet academic standards consistently."),
    ("static","adj./n. 静态的；静电","Static analysis versus dynamic listening."),
    ("status","n./v. 地位；状态","Check application status online."),
    ("steady","adj./v. 稳定的；稳固","Steady improvement in listening comprehension."),
    ("strategy","n. 战略；策略","Develop effective listening strategies."),
    ("stream","n./v. 溪流；流动","Stream audio files for listening practice."),
    ("stress","n./v. 压力；强调","Stress patterns affect listening comprehension."),
    ("strict","adj. 严格的","Strict attendance policy enforced in class."),
    ("structure","n./v. 结构；构造","Recognize lecture structure for main ideas."),
    ("style","n./v. 风格；样式","Professors have different speaking styles."),
    ("subject","n./adj./v. 主题；学科","Lecture subject changes week to week."),
    ("submit","v. 提交；服从","Submit assignments before specified deadline."),
    ("subsequent","adj. 随后的","Listen for subsequent events in sequence."),
    ("subsidy","n. 补贴；津贴","Government subsidy reduces student tuition cost."),
    ("substantial","adj. 大量的；实质的","Substantial evidence presented in talk."),
    ("succeed","v. 成功；继承","Students succeed through consistent listening practice."),
    ("sufficient","adj. 足够的；充分的","Sufficient examples provided in lecture."),
    ("suggest","v. 建议；暗示","Professor suggests additional reading materials."),
    ("supply","n./v. 供应；供给","Library supplies audio-visual learning materials."),
    ("support","v./n. 支持；支撑","Arguments support the thesis statement."),
    ("suppose","v. 假设；认为","Suppose the speaker meant something different."),
    ("supreme","adj. 最高的；极度的","Supreme effort required for listening tests."),
    ("surface","n./v. 表面；浮现","New information surfaced during discussion."),
    ("surpass","v. 超越；胜过","Surpass listening score expectations."),
    ("survey","n./v. 调查；测量","Survey results published in the report."),
    ("survive","v. 幸存；生存","Students survive through intensive listening practice."),
    ("suspect","v./n. 怀疑；嫌疑犯","Researchers suspect alternative explanation."),
    ("suspend","v. 暂停；悬挂","University suspended classes temporarily."),
    ("sustain","v. 维持；支撑","Sustain concentration during long listening."),
    ("symbol","n. 符号；象征","Mathematical symbols explained in lecture."),
    ("systematic","adj. 系统的","Systematic listening improves gradually."),
    ("tangible","adj. 有形的；切实的","Tangible benefits include improved scores."),
    ("target","n./v. 目标；针对","Target specific listening skills for improvement."),
    ("technique","n. 技术；技巧","Note-taking technique aids listening.")]

for a, b, c in listening_list:
    w(a, b, c, "听力")
print(f"听力: {len(V)}")

# 自然地理 30
geo_list = [
    ("tendency","n. 倾向；趋势","There is tendency toward warmer temperatures."),
    ("tension","n./v. 紧张；张力","Political tension affects resource management."),
    ("term","n./v. 术语；学期","Geographic terms defined in textbook."),
    ("terminal","n./adj. 终端；末端","Bus terminal located near city center."),
    ("theme","n./v. 主题；题目","Climate change theme in recent reports."),
    ("theoretical","adj. 理论的","Theoretical models predict geographic shifts."),
    ("theory","n. 理论；学说","Theory of plate tectonics explained geography."),
    ("thesis","n. 论文；论点","Geography thesis discusses desertification."),
    ("therefore","adv. 因此；所以","Sea levels rising; therefore coastal risk grows."),
    ("thorough","adj. 彻底的；详细的","Thorough analysis of geographic data."),
    ("thought","n. 思想；思考","Critical thought applied to geographic issues."),
    ("threat","n. 威胁；恐吓","Deforestation threat to biodiversity."),
    ("threshold","n. 门槛；临界；阈值","Crossing threshold of climate change."),
    ("thrive","v. 兴旺；茁壮成长","Wildlife thrives in protected ecosystems."),
    ("tolerate","v. 忍受；容忍","Species tolerate specific temperature ranges."),
    ("topic","n. 题目；话题","Ocean currents topic in geography class."),
    ("total","adj./n./v. 总共；总计","Total forest area declining annually."),
    ("tough","adj. 坚韧的；困难的","Tough environmental challenges facing humanity."),
    ("trace","v./n. 追踪；痕迹","Trace origins of rivers on maps."),
    ("track","n./v. 轨道；跟踪","Track weather patterns across regions."),
    ("tradition","n. 传统；惯例","Geographic study has long academic tradition."),
    ("trait","n. 特征；特点；特性","Regional traits influence local geography."),
    ("transform","v. 改变；使改观","Urbanization transforms natural landscapes."),
    ("translate","v. 翻译；转化","Translate geographic data into maps."),
    ("transmit","v. 传输；传播","Weather satellites transmit data hourly."),
    ("transport","n./v. 运输；运送","Transport infrastructure affects geography."),
    ("trend","n./v. 趋势；倾向","Global warming trend documented extensively."),
    ("trigger","v./n. 触发；扳机","Deforestation triggers ecological change."),
    ("trivial","adj. 琐碎的；不重要的","Seemingly trivial factors affect climate."),
    ("tropical","adj. 热带的；热情的","Tropical rainforests are biodiversity hotspots.")]

for a, b, c in geo_list:
    w(a, b, c, "自然地理")
print(f"自然地理: {len(V)}")

# 科技发明 30
tech_list = [
    ("turbulent","adj. 动荡的；湍流的","Turbulent tech industry changes rapidly."),
    ("typical","adj. 典型的；特有的","Typical computer features change yearly."),
    ("ubiquitous","adj. 无处不在的","Smartphones are ubiquitous in modern life."),
    ("ultimately","adv. 最终；根本上","Technology ultimately shapes our future."),
    ("undergo","v. 经历；遭受","Computers undergo constant upgrades."),
    ("underline","v. 强调；在下面划线","Figures underline technology's importance."),
    ("understand","v. 理解；懂得","Understand principles behind the technology."),
    ("uniform","adj./n. 统一的；制服","Uniform standard adopted industry-wide."),
    ("unique","adj. 独特的；唯一的","Each invention has unique characteristics."),
    ("unit","n. 单位；单元","Computing unit processes data efficiently."),
    ("unite","v. 联合；合并","Technologies unite people across distances."),
    ("universal","adj. 普遍的；通用的","Technology has universal applications."),
    ("unknown","adj./n. 未知的","Unknown consequences of new technologies."),
    ("update","v./n. 更新；修正","Software updates released periodically."),
    ("upgrade","v./n. 升级；提升","Hardware upgrades improve performance."),
    ("upload","v. 上传","Students upload assignments via portals."),
    ("urban","adj. 城市的；都市的","Urban tech infrastructure enables smart cities."),
    ("urge","v./n. 催促；迫切要求","Experts urge investment in research."),
    ("usable","adj. 可用的；合用的","User interface makes software usable."),
    ("utility","n. 效用；实用；公用事业","Utility of artificial intelligence debated."),
    ("utilize","v. 利用；使用","Researchers utilize advanced data analysis."),
    ("vague","adj. 模糊的；含糊的","Early technology descriptions can be vague."),
    ("valid","adj. 有效的；有根据的","Valid patent protects the invention."),
    ("valuable","adj. 有价值的","Technology creates valuable opportunities."),
    ("variable","adj./n. 可变的；变量","Speed is variable depending on hardware."),
    ("variation","n. 变化；变异","Variation exists between different models."),
    ("variety","n. 多样；种类","Variety of tech solutions available."),
    ("various","adj. 各种各样的","Various inventions transformed daily life."),
    ("vary","v. 变化；不同","Results vary by technological approach."),
    ("vast","adj. 广阔的；巨大的","Vast data processed by modern algorithms.")]

for a, b, c in tech_list:
    w(a, b, c, "科技发明")
print(f"科技发明: {len(V)}")

# 身心健康 20
health_list = [
    ("vehicle","n. 车辆；交通工具","Vehicle emissions affect public health."),
    ("version","n. 版本；说法","New version of software released today."),
    ("veteran","n./adj. 老兵；经验丰富的","Veteran researchers guide new scientists."),
    ("via","prep. 通过；经由","Information travels via internet rapidly."),
    ("viable","adj. 可行的；能养活的","Health solutions must be economically viable."),
    ("vibrant","adj. 充满活力的","Healthy cities have vibrant community life."),
    ("video","n./adj. 视频；录像","Video conferencing supports remote health consult."),
    ("view","n./v. 观点；景色","Alternative views on health treatment exist."),
    ("violate","v. 违反；违背","Never violate medical confidentiality."),
    ("virtual","adj. 虚拟的","Virtual reality assists health therapy."),
    ("virtue","n. 美德；优点","Patience is a virtue for healthcare workers."),
    ("visible","adj. 可见的；明显的","Visible signs of improvement appear."),
    ("vision","n. 视力；视野；愿景","Good vision important for reading students."),
    ("vital","adj. 至关重要的","Water and sleep are vital for health."),
    ("vivid","adj. 生动的；鲜明的","Mindfulness creates vivid present awareness."),
    ("voluntary","adj. 自愿的","Voluntary health screening recommended."),
    ("vote","v./n. 投票；选票","Communities vote on health infrastructure."),
    ("vulnerable","adj. 脆弱的；易受攻击的","Children are vulnerable health group."),
    ("wellness","n. 健康；幸福","Wellness programs improve student life."),
    ("welfare","n. 福利；幸福","Government welfare supports public health.")]

for a, b, c in health_list:
    w(a, b, c, "身心健康")
print(f"身心健康: {len(V)}")

# 文化历史 20
culture_list = [
    ("heritage","n. 遗产；继承物","Cultural heritage preserved in museums."),
    ("tradition","n. 传统；惯例","Traditions pass from generation to generation."),
    ("historical","adj. 历史的","Historical records document past cultures."),
    ("civilization","n. 文明；文化","Ancient civilizations invented writing."),
    ("archaeology","n. 考古学","Archaeology reveals ancient culture details."),
    ("artifact","n. 人工制品；文物","Artifacts preserved from historical sites."),
    ("cultural","adj. 文化的","Cultural exchange promotes understanding."),
    ("custom","n. 习惯；风俗","Local customs vary across regions."),
    ("heritage","n. 遗产","World Heritage sites protected internationally."),
    ("legend","n. 传奇；传说","Legends describe historical events mythically."),
    ("myth","n. 神话；虚构的事","Myths explain natural phenomena."),
    ("ritual","n./adj. 仪式；典礼","Rituals mark important cultural events."),
    ("ceremony","n. 典礼；仪式","Graduation ceremony celebrates achievement."),
    ("folklore","n. 民间传说；民俗","Folklore transmitted orally for centuries."),
    ("ancestor","n. 祖先；祖宗","Ancestors contribute to cultural identity."),
    ("heritage","n. 传统；遗产","Language carries cultural heritage forward."),
    ("celebration","n. 庆祝；庆典","Celebrations reflect cultural values."),
    ("ceremonial","adj. 仪式的","Ceremonial clothing worn at special events."),
    ("civilize","v. 使文明；教化","Education civilizes and enlightens."),
    ("ethnic","adj. 种族的；民族的","Ethnic diversity enriches culture.")]

for a, b, c in culture_list:
    w(a, b, c, "文化历史")
print(f"文化历史: {len(V)}")

# 同义替换 20
synonym_list = [
    ("nevertheless","adv. 然而；不过","Nevertheless: however, yet, still."),
    ("furthermore","adv. 此外；而且","Furthermore: moreover, additionally."),
    ("consequently","adv. 因此；所以","Consequently: therefore, hence, thus."),
    ("moreover","adv. 而且；此外","Moreover: furthermore, in addition."),
    ("therefore","adv. 因此；所以","Therefore: consequently, accordingly."),
    ("however","adv. 然而；可是","However: nevertheless, yet, but."),
    ("although","conj. 尽管；虽然","Although: though, even though, while."),
    ("whereas","conj. 然而；鉴于","Whereas: while, although, conversely."),
    ("meanwhile","adv. 同时；其间","Meanwhile: concurrently, at the same time."),
    ("likewise","adv. 同样地；也","Likewise: similarly, in the same way."),
    ("otherwise","adv. 否则；不然","Otherwise: or else, differently."),
    ("accordingly","adv. 因此；相应地","Accordingly: therefore, consequently."),
    ("subsequently","adv. 随后；后来","Subsequently: afterwards, later, next."),
    ("presumably","adv. 可能；据推测","Presumably: probably, likely."),
    ("respectively","adv. 分别地；各自地","Respectively: each in turn, in order."),
    ("ultimately","adv. 最终；最后","Ultimately: finally, eventually, in the end."),
    ("predominantly","adv. 主要地；显著地","Predominantly: mainly, mostly."),
    ("approximately","adv. 大约；近似地","Approximately: about, roughly, around."),
    ("particularly","adv. 特别地；尤其","Particularly: especially, specifically."),
    ("simultaneously","adv. 同时地","Simultaneously: at the same time, concurrently.")]

for a, b, c in synonym_list:
    w(a, b, c, "同义替换")
print(f"同义替换: {len(V)}")

# 学校教育 10
edu_list = [
    ("curriculum","n. 课程","School curriculum prepares students broadly."),
    ("pedagogy","n. 教育学；教学法","Modern pedagogy emphasizes student engagement."),
    ("assessment","n. 评价；评估","Continuous assessment measures progress."),
    ("scholarship","n. 奖学金；学识","Scholarships support talented students."),
    ("semester","n. 学期","Academic year divided into two semesters."),
    ("syllabus","n. 教学大纲；课程提纲","Syllabus outlines course requirements."),
    ("tuition","n. 学费","Tuition fees vary between institutions."),
    ("attendance","n. 出勤；出席","Regular attendance correlates with achievement."),
    ("enrollment","n. 注册；入学","Enrollment numbers increase annually."),
    ("transcript","n. 成绩单；抄本","Official transcript shows academic record.")]

for a, b, c in edu_list:
    w(a, b, c, "学校教育")
print(f"学校教育: {len(V)}")

# 语法 10
grammar_list = [
    ("tense","n./adj. 时态；紧张的","Verb tense indicates time of action."),
    ("subject","n. 主语；主题","Subject agrees with verb in number."),
    ("predicate","n./v. 谓语；断言","Predicate describes subject's action."),
    ("clause","n. 从句；条款","Complex sentences contain multiple clauses."),
    ("phrase","n./v. 短语；措辞","Phrase is group of related words."),
    ("conjunction","n. 连词；结合","Conjunction connects clauses or phrases."),
    ("preposition","n. 介词","Preposition shows relationship between words."),
    ("modifier","n. 修饰语；修饰成分","Modifier adds detail to sentence element."),
    ("article","n. 冠词；文章","Articles specify noun definiteness."),
    ("noun","n. 名词","Noun names person, place, thing, or idea.")]

for a, b, c in grammar_list:
    w(a, b, c, "语法")
print(f"语法: {len(V)}")

print(f"Total vocabulary: {len(V)}")
with open('/workspace/public/data/vocabulary-seed.json','w',encoding='utf-8') as f:
    json.dump(V, f, ensure_ascii=False, indent=2)
print("vocabulary-seed.json written")
