import json

data = [
    # Task 1 - 8 items
    {
        "type":"Task1",
        "topic":"Bar Chart - Energy Production",
        "prompt":"The chart below shows the amounts of energy produced from different sources in a European country between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        "sample_outline":"1. Introduce what the bar chart describes (time period, location, energy sources). 2. Give an overview: which sources increased, decreased, or remained stable; overall trends in renewable versus fossil fuels. 3. Detail the rise of wind and solar energy with specific figures. 4. Describe the decline of coal and the relatively stable natural gas production. 5. Briefly mention nuclear energy and compare total production across years.",
        "sample_essay":"The bar chart compares energy production from five different sources—coal, natural gas, nuclear, wind, and solar—over two decades, from 2000 to 2020, in a single European country. Overall, renewable energy production rose dramatically while fossil fuel generation declined, reflecting a shift toward cleaner energy sources. In 2000, coal was the dominant source at approximately 300 terawatt hours, but this figure had halved by 2020. Natural gas output remained relatively stable at between 200 and 220 terawatt hours throughout the period. Nuclear energy, meanwhile, increased moderately from around 120 to nearly 180 terawatt hours. The most striking change was in wind and solar energy. Wind power generation started at just 15 terawatt hours in 2000 but surged to 160 terawatt hours by 2020, while solar energy rose from negligible levels to approximately 90 terawatt hours. These increases were consistent with broader European efforts to reduce carbon emissions and transition to sustainable energy systems."
    },
    {
        "type":"Task1",
        "topic":"Line Graph - Urban Population Growth",
        "prompt":"The graph below shows changes in the percentage of people living in cities in four different countries from 1950 to 2020, with projections to 2050. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        "sample_outline":"1. Introduce the line graph showing urbanization trends across four countries over a century. 2. Summarize the overall trend of increasing urban population in all four nations, with some converging by 2050. 3. Compare the highest and lowest starting points in 1950 and describe the steepest increases. 4. Report on projected figures for 2050 and compare growth rates. 5. Note any interesting patterns such as countries overtaking each other.",
        "sample_essay":"The line graph illustrates the proportion of people living in urban areas in four different countries over the period from 1950 to 2020, with predicted trends until 2050. Overall, all four countries show a clear upward trend in urban population, with the most dramatic growth occurring in developing nations. In 1950, Country A had the highest level of urbanization at roughly 60%, followed by Country B at approximately 45%. Countries C and D had the lowest urban populations, standing at around 20% and 15% respectively. By 2020, Country A still led at approximately 80%, while Country C had experienced the most rapid increase, reaching nearly 70%. Looking ahead to 2050, the forecast suggests that urbanization levels in all four countries will continue rising, with figures converging toward the 80% to 90% range. Country D is predicted to show the steepest growth, while Country A maintains its lead but with slower growth. These trends reflect a broader global pattern of population movement from rural areas toward cities, driven by economic opportunities and improved urban infrastructure."
    },
    {
        "type":"Task1",
        "topic":"Pie Chart - Household Expenditure",
        "prompt":"The charts below show the percentage of household expenditure on different categories in two countries in 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        "sample_outline":"1. Introduce the two pie charts showing household spending categories in two nations across two years. 2. Summarize the main similarities and differences between the two countries and how spending patterns changed. 3. Compare spending on essentials such as food, housing, and transport in both countries. 4. Describe changes in leisure, education, and healthcare expenditure. 5. Conclude with observations on convergence or widening differences.",
        "sample_essay":"The two sets of pie charts compare household expenditure patterns across six categories in two countries during 2010 and 2020. Overall, while Country X consistently allocated more spending to essential items like food and housing, Country Y devoted a larger proportion to leisure and transport. Over the decade, housing costs rose in both nations while spending on food declined. In 2010, residents of Country X spent approximately 35% of their budget on food and 25% on housing, compared with 20% and 30% respectively in Country Y. Ten years later, food spending had dropped to around 28% in Country X while housing had climbed to 32%, mirroring a similar shift in Country Y where housing reached 35% and food fell to 15%. Meanwhile, expenditure on leisure activities increased slightly in both countries, rising from 12% to 18% in Country Y and from 8% to 12% in Country X. Education and healthcare spending remained relatively stable at below 10% in both nations. These shifts suggest that households in both countries faced rising accommodation costs while allocating proportionally less to food, possibly due to declining real food prices and higher disposable incomes."
    },
    {
        "type":"Task1",
        "topic":"Table - International Student Enrolment",
        "prompt":"The table below shows the number of international students enrolled in universities in three English-speaking countries in 2005, 2010, and 2015. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        "sample_outline":"1. Introduce the table showing international student numbers across three countries over three periods. 2. Provide an overview: which country was most popular, which grew fastest, overall trend upward. 3. Detail figures for the most popular country, including student origins and growth rate. 4. Compare the other two countries, reporting increases or decreases and ranking changes. 5. Comment on the proportion from different regions.",
        "sample_essay":"The table provides figures for the number of international students attending university in three major English-speaking countries during 2005, 2010, and 2015, broken down by geographic origin. Overall, all three countries saw rising international enrolment, though at different rates, with Country A consistently attracting the largest numbers throughout the period. In 2005, Country A hosted approximately 250,000 overseas students, more than double the figure for Country B at 120,000 and considerably higher than Country C's 80,000. By 2015, Country A's international student population had grown to 420,000, while Country B and Country C reached 210,000 and 195,000 respectively, representing faster percentage growth despite lower absolute numbers. Students from East Asia constituted the largest group in all three countries, followed by European and South Asian students. Country B and Country C experienced particularly strong growth in enrolments from Africa and the Middle East. These figures reflect the increasing globalization of higher education and growing demand from emerging economies for overseas degree programs at English-language institutions."
    },
    {
        "type":"Task1",
        "topic":"Process Diagram - Coffee Production",
        "prompt":"The diagram below shows the process by which coffee is produced, from the growing of beans to the packaging of finished products. Summarise the information by selecting and reporting the main stages, and make comparisons where relevant.",
        "sample_outline":"1. Introduce the process diagram showing coffee production stages from cultivation to consumer packaging. 2. Provide overview: describe that the process is linear with multiple stages, highlighting key transformation points. 3. Outline the early stages in agricultural production: planting, harvesting, and initial processing on the farm. 4. Describe the intermediate industrial stages: drying, roasting, grinding, and packaging. 5. Briefly mention distribution and retail as final steps before reaching consumers.",
        "sample_essay":"The process diagram illustrates the various stages involved in the commercial production of coffee, starting with cultivation and ending with the distribution of packaged products to consumers. Overall, coffee production involves approximately ten interconnected stages, combining agricultural work with industrial processing and commercial packaging. The process commences with the planting of coffee trees in suitable tropical climates, followed by several years of growth before the plants yield fruit. Once the cherries ripen, they are harvested either by hand or mechanically. The harvested fruits then undergo an initial processing stage in which the outer flesh is removed, revealing the green coffee beans inside. These beans are subsequently dried under the sun for several weeks before being sorted and graded according to size and quality. Following sorting, the green beans are roasted at carefully controlled temperatures to develop their characteristic flavor and aroma. After roasting, the beans are allowed to cool and are then ground, sometimes mixed with water to create liquid extracts for instant coffee products. The resulting ground coffee or instant powder is sealed in airtight containers, labeled, and packaged. Finally, the finished products are distributed to retail outlets such as supermarkets and cafes where they become available for purchase by consumers."
    },
    {
        "type":"Task1",
        "topic":"Map - Town Development",
        "prompt":"The maps below show the changes that have taken place in a town over the past thirty years, from 1990 to 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        "sample_outline":"1. Introduce the two maps showing the same town in 1990 and 2020. 2. Overview: summarize the major developments - urban expansion, new infrastructure, and reduced agricultural land. 3. Describe specific changes in the central area including new buildings and transport links. 4. Detail changes on the outskirts and surrounding countryside. 5. Mention environmental or recreational developments such as parks.",
        "sample_essay":"The two maps illustrate how a town developed over the thirty-year period from 1990 to 2020. Overall, the settlement expanded significantly, with new residential and commercial areas replacing agricultural land, while infrastructure such as roads and public facilities improved substantially. In 1990, the town was relatively small, with a main shopping street running east to west, a small residential area to the north, and extensive farmland to the south and east. Thirty years later, the residential zone had expanded dramatically, with hundreds of new houses built on previously rural land to the north and west. A new ring road had been constructed to connect these neighborhoods, and a large shopping mall with parking facilities had replaced several older buildings in the town center. Additionally, a hospital and a secondary school were built on the southern side, while the eastern farmland had been converted into a public park with trees, a lake, and sports facilities. The original train station was renovated and expanded, and a new bus terminal was added near the town center. These developments reflect typical trends of suburban growth as populations increase and rural areas are absorbed into urban centers."
    },
    {
        "type":"Task1",
        "topic":"Multiple Charts - Internet Usage",
        "prompt":"The chart and table below give information about internet usage by age group in a particular country in 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        "sample_outline":"1. Introduce the mixed chart and table showing internet usage across age groups over two decades. 2. Overview: overall growth across all ages, especially among older groups; narrowing generational gap. 3. Describe the chart showing percentage of users by age in 2000 with highest among younger users. 4. Describe 2020 figures showing substantial increase across older age groups. 5. Present the table detailing daily hours online and most popular activities by age.",
        "sample_essay":"The bar chart and accompanying table provide data about internet usage patterns in a single country during 2000 and 2020, broken down by five age categories. Overall, internet use increased dramatically across all age groups over the two decades, with older age groups showing the most substantial growth, though younger people remained the heaviest users throughout. In 2000, internet access was largely limited to younger demographics, with approximately 80% of those aged 15 to 25 using the internet regularly, compared with only 10% of people aged 65 and over. By 2020, however, usage rates had risen substantially in all groups; even the oldest category had reached 55%, while younger users had increased to nearly 100%. The table provides further details, showing that daily hours online also rose for each age group. Younger internet users spent roughly 4.5 hours online daily in 2020, up from 1.2 hours in 2000, while older users went from negligible daily usage to roughly 2 hours daily. Social networking and information search were the most popular online activities for younger age groups, whereas older users primarily accessed email, news, and health-related content. These figures illustrate the progressive integration of digital technology across the population regardless of age."
    },
    {
        "type":"Task1",
        "topic":"Bar Chart - Museum Visitors",
        "prompt":"The chart below shows the number of visitors to different types of museums in a city over three years. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
        "sample_outline":"1. Introduce the bar chart illustrating visitor numbers across five different museum categories over three consecutive years. 2. Overview: summarize which museums were most popular overall and which saw rising or falling attendance. 3. Detail the most popular museums with specific figures and year-on-year changes. 4. Describe visitor trends for the smaller or specialized institutions. 5. Comment on seasonal or event-driven fluctuations.",
        "sample_essay":"The bar chart compares visitor attendance across five different museum categories—art, natural history, science, history, and children's museums—over a three-year period. Overall, art museums and science museums were the most popular attractions throughout the period, while children's museums attracted the fewest visitors but showed the strongest growth. In the first year, art museums led with approximately 500,000 visitors, followed closely by science museums at around 470,000. Natural history and history museums each drew roughly 350,000 visitors, while children's museums attracted just 150,000. During the second year, however, visitor numbers to science museums rose sharply to nearly 600,000, overtaking art museums which experienced a slight decline, likely due to renovation work. By the third year, science museums retained their lead at 620,000 visitors, and art museums recovered to approximately 540,000. Children's museums grew substantially, reaching 280,000 visitors by the final year, almost double their initial figure. These shifting patterns may reflect the impact of temporary exhibitions, educational programming, and marketing efforts, with science and children's museums benefiting from renewed public interest in interactive learning experiences."
    },

    # Task 2 - 15 items
    {
        "type":"Task2",
        "topic":"Technology and education - Agree or disagree",
        "prompt":"Some people believe that technology such as computers and the internet will eventually replace the traditional role of teachers in the classroom. To what extent do you agree or disagree with this opinion? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: technology is transforming education but unlikely to replace teachers entirely; agree that technology changes teaching but disagree it will replace human educators. 2. First reason: technology provides tools for personalized learning and broad access to information, making lessons more engaging and adaptive. 3. Second reason: teachers offer essential emotional guidance, motivation, and moral education that machines cannot provide. 4. Third reason: interaction with teachers and classmates develops communication and social skills vital for adult life. 5. Conclusion: technology complements rather than replaces teachers; the best future combines both.",
        "sample_essay":"It is undeniable that digital technology has transformed how people learn and will continue reshaping education in the future. While computers and the internet offer powerful tools for instruction, I believe that teachers will remain central to effective learning and are unlikely to be replaced entirely. Technology undoubtedly offers significant advantages in education. Computers can deliver personalized lessons adapted to individual abilities, and students can access vast amounts of information online at any time. For example, language learning software can adjust exercises based on performance, helping learners improve specific weaknesses more efficiently than traditional whole-class teaching ever could. Digital tools also benefit students in remote areas where access to quality schools is limited, providing educational opportunities that would otherwise be unavailable. Despite these clear advantages, teachers fulfill essential roles that technology cannot replicate. First, skilled educators inspire motivation and confidence in their students, especially when learners face difficulties or lose interest. The emotional support that a dedicated teacher provides can make the difference between academic success and failure for many young people. Second, teachers help students develop critical thinking and moral reasoning through discussion, guiding pupils to evaluate information rather than absorb it passively. Furthermore, classrooms are social environments where interaction with teachers and peers builds communication skills, teamwork abilities, and cultural understanding. These social competencies cannot be developed through interaction with screens alone. In conclusion, while technology offers valuable educational tools and should be integrated into modern classrooms, it cannot replace the wisdom, experience, and human connection that good teachers provide. The most effective future education will likely combine the best of both, with technology enhancing rather than replacing the vital role of the teacher."
    },
    {
        "type":"Task2",
        "topic":"Environmental protection - Discuss both views",
        "prompt":"Some people believe that governments should invest heavily in protecting the environment even if it slows economic growth. Others argue that economic development should be the priority, as it creates the wealth needed to afford environmental protection later. Discuss both these views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: economic progress and environmental protection are often perceived as competing goals; present both views and thesis that balanced development is preferable. 2. First view: explain why environmental protection should take priority—irreversible damage, future generations' health, natural resources depletion. 3. Second view: explain why economic growth matters—wealth funds technology, reduces poverty, enables investment in cleaner systems. 4. Own opinion: argue that sustainable development integrating both goals offers the best path forward, with historical examples. 5. Conclusion: green growth strategies benefit both economy and environment.",
        "sample_essay":"The relationship between economic development and environmental protection has become one of the most debated issues of our time. While some people argue that governments must prioritize safeguarding nature even at the expense of short-term economic growth, others maintain that creating wealth is the necessary foundation for long-term environmental progress. This essay will discuss both perspectives and explain why I believe a balanced strategy of sustainable development is the most promising approach. Those who prioritize environmental protection argue that some forms of ecological damage are irreversible and therefore more urgent than economic gains. Destroying ancient forests, polluting oceans, and driving species to extinction cannot be undone, regardless of later wealth. Additionally, a damaged environment imposes enormous long-term costs on societies through poor health, reduced agricultural productivity, and costly cleanup operations. Investing in renewable energy, sustainable agriculture, and protected ecosystems therefore serves both present well-being and future prosperity. On the other hand, advocates of prioritizing economic growth contend that poor societies can ill afford environmental protection. Wealthier populations demand cleaner surroundings and possess the capital to develop cleaner technology; historically, industrialization preceded widespread environmental awareness and investment. Without economic development, impoverished communities may destroy natural resources simply to survive, through activities such as deforestation for farmland or overfishing for food. Sustainable development strategies that reconcile these two goals appear to offer the best solution. Many countries now demonstrate that green investment creates jobs, reduces energy costs, and protects ecosystems simultaneously. For instance, investing in renewable energy technology simultaneously reduces pollution while creating new industries and exports. In conclusion, both environmental protection and economic development are essential, but treating them as opposites is misleading. Governments should pursue policies that integrate both objectives, recognizing that long-term prosperity depends on a healthy planet."
    },
    {
        "type":"Task2",
        "topic":"Online shopping - Advantages and disadvantages",
        "prompt":"Online shopping has become increasingly popular in recent years, transforming the retail industry. Do the advantages of this development outweigh the disadvantages for consumers, businesses, and society as a whole? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: online shopping has grown exponentially; while it offers benefits including convenience and lower prices, it also creates problems. 2. Advantages for consumers: convenience, wider selection, better pricing through comparison shopping, accessibility for disabled or rural customers. 3. Advantages for businesses: reduced overhead costs, access to global markets, data-driven marketing; benefits to society include job creation in logistics and tech sectors. 4. Disadvantages: loss of personal service, fraud risks, environmental impact of packaging and transport, decline of local shops and city centers. 5. Conclusion: advantages outweigh disadvantages overall, but policies should mitigate harms.",
        "sample_essay":"The growth of online commerce has fundamentally reshaped how people shop for goods and services worldwide. While digital retailing has brought substantial benefits for consumers and businesses alike, it has also introduced new social and economic challenges. This essay will consider both the advantages and disadvantages of online shopping before concluding whether its overall impact has been positive. Online shopping offers consumers undeniable advantages in convenience, price, and selection. Purchasing from home at any hour saves the time and cost of traveling to physical stores, and customers can easily compare prices across dozens of retailers within seconds. Internet retailers also offer far wider product selections than traditional stores could stock, including specialized or international items unavailable locally. For businesses, online operations typically reduce expenses related to physical premises and staffing, while enabling them to reach customers across national borders without costly international expansion. These savings can then be passed to consumers through lower prices. Furthermore, the rise of e-commerce has created millions of jobs globally in logistics, software development, and digital marketing. Despite these benefits, online shopping introduces several disadvantages. The shift away from physical shops has accelerated the decline of city centers and small local businesses, reducing community life and sometimes increasing unemployment in traditional retail. Environmental costs are also significant; online shopping generates enormous volumes of packaging waste and frequent home deliveries increase urban traffic and pollution. Additionally, customers lose the personal service and immediate product inspection that physical shopping offers, and online fraud remains a persistent risk. In conclusion, although online shopping has genuine drawbacks that require careful management, its overall benefits in convenience, affordability, and accessibility make it a positive development overall. Governments should help traditional retailers adapt, encourage greener delivery practices, and enforce stronger consumer protection to maximize the advantages while minimizing the harms of this transformative economic shift."
    },
    {
        "type":"Task2",
        "topic":"Work and career - Problems and solutions",
        "prompt":"In many countries, young people find it increasingly difficult to secure satisfying, well-paid employment after graduation, even with university degrees. What are the causes of this problem, and what measures could be taken to address it? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: youth unemployment is a growing global problem, even among graduates; multiple causes require coordinated solutions. 2. Causes: oversupply of graduates in popular fields, insufficient vocational skills, economic shifts away from manufacturing, geographic mismatch between jobs and graduates. 3. Additional causes: high employer expectations, growing competition from international graduates, inadequate career guidance in universities. 4. Solutions: universities should reform curricula to include practical training and internships; governments should subsidize vocational programs and emerging industries; students should diversify skills and consider geographic mobility. 5. Conclusion: combined efforts of government, education, and individuals required.",
        "sample_essay":"Securing meaningful, well-paid employment has become a serious challenge for many university graduates worldwide, despite years of investment in education. This growing problem stems from multiple economic and educational factors, and addressing it requires coordinated action from governments, educational institutions, and young people themselves. Several interconnected factors help explain rising graduate unemployment. First, the number of university graduates has increased substantially in recent decades, leading to oversupply in popular fields such as law, humanities, and business administration where job growth has not kept pace with enrolment. Second, rapid technological change and automation have eliminated or transformed traditional jobs faster than educational systems can adapt, leaving graduates with outdated skills. Furthermore, economic globalization means that graduates now compete with international candidates for the same positions. In many countries, university education remains overly theoretical, providing insufficient practical training or work experience, so employers complain that even qualified graduates lack immediately useful workplace skills. Finally, high housing costs in major employment hubs create geographic barriers preventing new graduates from relocating to where jobs are most abundant. Addressing this challenge requires multiple complementary solutions. Universities should reform their curricula to balance theory with practical skills such as communication, teamwork, and digital competence, and expand mandatory internships with partner companies. Governments should expand subsidies for vocational training in growing fields such as healthcare, technology, and renewable energy, while also supporting job creation through investment in infrastructure and emerging industries. Young people themselves could improve their prospects by seeking international experience, mastering digital skills, and remaining flexible about geographic location and initial job levels. In conclusion, graduate unemployment reflects deep economic and educational mismatches that no single party can resolve alone. By combining educational reform, government support, and personal initiative, societies can help more young people build successful and satisfying careers in a rapidly changing world of work."
    },
    {
        "type":"Task2",
        "topic":"Public health - Causes and effects",
        "prompt":"Rates of obesity and related health problems have been rising rapidly in many countries around the world. What are the primary causes of this trend, and what effects does it have on individuals and societies? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: obesity has become a global public health crisis; multiple environmental and lifestyle causes create serious personal and social consequences. 2. Causes: changes in diet toward processed, calorie-dense food; increasingly sedentary lifestyles due to office work and digital entertainment; urbanization reducing opportunities for walking and exercise. 3. Additional causes: food industry marketing of unhealthy products, stressed lifestyles encouraging emotional eating, subsidized agricultural policies favoring unhealthy commodity crops. 4. Effects on individuals: physical illness including diabetes and heart disease, reduced mobility, emotional distress and reduced quality of life. Effects on society: rising healthcare costs, lost economic productivity, strain on public health budgets. 5. Conclusion: requires comprehensive government action including regulation, education, and urban planning.",
        "sample_essay":"Obesity and the health problems associated with it have escalated dramatically worldwide in recent decades, now affecting both wealthy and middle-income countries. This worrying trend results from fundamental changes in diet, work, and urban life, and it imposes severe costs on both individuals and societies. Several interconnected factors explain the global rise in obesity. Perhaps most significant is the shift toward diets dominated by processed, calorie-dense foods that are high in sugar, unhealthy fats, and salt. Such products are aggressively marketed, inexpensive, and widely available, making them default choices for busy families. Simultaneously, lifestyles have become far more sedentary as technology reduces physical activity in the home, workplace, and transport. People spend long hours sitting at computers, and leisure time is increasingly spent indoors watching television or using digital devices rather than exercising outdoors. Urbanization further contributes by designing cities around cars rather than pedestrians or cyclists, making walking and cycling inconvenient or dangerous. Agricultural policies that subsidize commodity crops such as corn and soybeans also make unhealthy processed food artificially cheap compared with fresh produce. The consequences of rising obesity are serious and wide-ranging. For individuals, excess weight increases the risk of chronic conditions including type two diabetes, cardiovascular disease, certain cancers, and joint problems, significantly reducing life expectancy and quality of life while causing emotional distress through social stigma. At a societal level, obesity-related illnesses impose enormous costs on public health systems, absorbing resources that could be used elsewhere. They also reduce economic productivity by increasing sick leave and disability while raising insurance costs for everyone. In the most affected countries, healthcare spending on obesity-related conditions now represents a significant proportion of national budgets. In summary, the rise of obesity reflects broad societal trends that are difficult to reverse through individual willpower alone. Effectively addressing this crisis will require coordinated government action, including better regulation of food marketing, improved urban design for active living, public education campaigns, and policies making nutritious food more affordable and accessible for all."
    },
    {
        "type":"Task2",
        "topic":"Global language - Agree or disagree",
        "prompt":"Some people believe that a single global language would promote international understanding and economic development, while others argue that this would lead to the loss of cultural identity and diversity. Discuss both these views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: English is increasingly dominant worldwide; a truly global language offers practical benefits but threatens linguistic and cultural diversity. 2. Argument for a single global language: facilitates trade, education, diplomacy, and scientific cooperation; reduces translation costs and misunderstandings; connects people globally. 3. Argument against: erodes cultural identity, reduces diversity of thought, weakens minority communities; language loss represents irreversible loss of human history and knowledge. 4. Own opinion: international lingua franca is beneficial and perhaps inevitable in the digital age, but it must coexist with strong local languages; multilingualism is the ideal. 5. Conclusion: encourage bilingualism and multilingual policies so that global communication coexists with cultural richness.",
        "sample_essay":"The spread of English as a dominant international language has led some to argue that the world would benefit from adopting a single global language, while others fear that such a development would cause irreversible cultural loss. This essay will discuss both perspectives before concluding that linguistic diversity and global communication can and should coexist. A single global language would offer undeniable practical advantages. International trade, scientific research, diplomatic negotiations, and online communication all depend on shared linguistic conventions, and translation costs and misunderstandings impede cooperation. A common language would simplify commerce, accelerate knowledge sharing, and bring people closer culturally by enabling direct personal communication across national borders. Proponents argue that in an increasingly interdependent world, linguistic barriers are unnecessary obstacles to progress. Scientific research in particular would advance faster if findings spread without language delays, and developing countries would find it easier to participate in global economic opportunities. However, critics of linguistic globalization point out that language is far more than a practical tool; it embodies culture, history, and identity. When languages disappear, unique systems of thought, traditional knowledge, and cultural expressions disappear with them. Linguistic diversity enriches humanity much as biodiversity enriches nature, and the loss of either impoverishes future generations. Minority communities are especially vulnerable; as younger generations abandon ancestral languages for dominant global ones, communities lose cultural continuity and self-esteem. Furthermore, a single global language might inadvertently entrench cultural and political dominance by the nations whose language is adopted. In my opinion, a thriving global lingua franca such as English and the preservation of linguistic diversity need not be mutually exclusive. The most beneficial outcome would be widespread bilingualism or multilingualism, with international languages serving practical communication while local languages remain strong in family, community, and cultural life. Governments should support education in both international and local languages, and societies should value multilingualism as an asset rather than a burden. In conclusion, while shared languages bring undeniable practical benefits, protecting linguistic diversity is equally important for cultural richness and human heritage. Thoughtful policies can help societies enjoy the advantages of global communication while preserving the depth and variety of human expression embodied in thousands of living languages."
    },
    {
        "type":"Task2",
        "topic":"Public transport - Agree or disagree",
        "prompt":"Some people argue that governments should invest significantly more money in improving public transport systems to reduce traffic congestion and pollution. Others suggest that building more and wider roads is a better solution. Discuss both these views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: urban traffic congestion is worsening globally; debate between better public transport versus more road capacity. 2. Argument for public transport investment: reduces car dependency, lowers pollution, decreases congestion, cheaper for users, equitable for non-drivers, uses space more efficiently. 3. Argument for road construction: immediate relief for drivers, supports commercial transport, cheaper infrastructure politically, accommodates growing vehicle fleets in developing cities. 4. Own opinion: while temporary road expansion may be necessary, heavy investment in public transit and active transport is more sustainable long term; successful cities worldwide demonstrate this. 5. Conclusion: balanced strategy combining public transit investment with careful road planning, disincentivizing car use in dense areas.",
        "sample_essay":"Traffic congestion and the pollution it causes have become defining problems of modern urban life, costing economies billions in lost productivity while damaging public health. Two competing strategies are commonly proposed: heavy investment in public transport or the construction of more and wider roads. This essay will discuss both approaches before concluding that public transport offers the more sustainable long-term solution, though a balanced strategy is often necessary. Advocates of expanded public transport argue that high-quality, affordable systems are the only realistic means of reducing car dependency in dense cities. Efficient buses, subways, and tram networks use road space far more efficiently than private cars, moving dozens or hundreds of passengers per vehicle instead of one or two. Reliable public transit also reduces urban pollution because modern electric or hybrid systems produce significantly lower emissions per passenger than private automobiles. Moreover, public transport benefits all residents including the young, elderly, and those unable to drive, improving equity in ways that road construction cannot. Cities with excellent transit systems, such as Singapore or Zurich, consistently show lower congestion and better quality of life. On the other hand, proponents of road expansion maintain that wider roads and new highways provide immediate relief by increasing overall capacity. In developing cities where transport infrastructure lags population growth, road construction may be the quickest way to unlock economic development by improving freight and commuter flows. Furthermore, improved roads can sometimes generate economic benefits that indirectly fund better public services later. However, research consistently demonstrates that road expansion alone rarely solves congestion long-term, because increased capacity tends to attract additional driving, eventually filling the new roads again—a phenomenon known as induced demand. In my opinion, while selective road improvements may sometimes be necessary, heavy investment in public transport combined with policies that discourage car use in dense urban areas is the most sustainable path. Cities should simultaneously invest in buses, rail systems, and cycling infrastructure while raising parking costs and limiting car access in city centers. In conclusion, road construction alone is a temporary and ultimately self-defeating solution to congestion. Permanent reduction in traffic requires reliable, affordable public transport supported by disincentives for private car use in dense cities. Governments should prioritize long-term sustainability over short-term relief in their transport planning."
    },
    {
        "type":"Task2",
        "topic":"Technology and privacy - Problems and solutions",
        "prompt":"The widespread collection of personal data by online companies and governments has raised serious concerns about privacy in the digital age. What are the most serious problems caused by this trend, and what practical solutions can you suggest? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: digital technology enables massive data collection; while valuable, this trend threatens privacy and personal freedom. 2. Problem 1: identity theft, financial fraud, and unauthorized surveillance by criminals or authoritarian governments. 3. Problem 2: erosion of personal autonomy through manipulative advertising and political micro-targeting based on data analysis. 4. Problem 3: chilling effect on free speech and political dissent when citizens know their activities are monitored. 5. Solutions: stronger data protection laws, transparent company policies, technology enabling user control, user education, enforcement of penalties for abuse. 6. Conclusion: privacy requires coordinated legal, technical, and social protection.",
        "sample_essay":"Digital technology has enabled governments and corporations to collect, store, and analyze enormous volumes of personal information, transforming services but also raising profound concerns about individual privacy. While some data collection supports convenience and security, its scale and opacity create serious problems that require practical legal and technical solutions. The most immediate risk of unrestricted data collection is financial loss and identity theft. Personal information collected online is frequently vulnerable to hacking, and breaches have exposed millions of citizens to fraud, financial damage, and identity theft. Beyond financial harm, personal data can enable mass surveillance and political repression, particularly in societies lacking strong legal protections. Authoritarian governments have used social media data and surveillance technology to track activists and suppress dissent, chilling political freedom even in nominally democratic contexts. Even in liberal societies, pervasive data collection enables increasingly sophisticated manipulation. Companies and political campaigns analyze personal preferences and browsing habits to deliver highly targeted content, subtly influencing consumer behavior and voting patterns in ways that users rarely understand. This erodes personal autonomy and may distort democratic processes. Furthermore, the knowledge that one's communications and location are recorded discourages free expression and honest debate. To address these issues, several practical measures should be adopted. First, governments should enact strict data protection laws requiring clear user consent, limiting the data that organizations may store, and imposing substantial penalties for abuse. Second, technology companies should be legally required to respect privacy by design, making protection the default rather than an afterthought. Third, users themselves need better education about digital privacy risks and simple tools to manage their own data. Finally, independent agencies should supervise government surveillance and audit corporate data practices to ensure compliance. In conclusion, while data collection enables valuable digital services, it also threatens privacy, autonomy, and freedom in ways not fully understood when these technologies were developed. Stronger legislation, improved technology, user awareness, and independent oversight together can help societies enjoy the benefits of digital life while protecting the personal privacy essential to free and dignified human existence."
    },
    {
        "type":"Task2",
        "topic":"Learning at home versus school - Agree or disagree",
        "prompt":"Some parents believe that educating children at home provides a more flexible and personalized learning experience than traditional schools. Others argue that children benefit enormously from attending school with peers and professionally trained teachers. Discuss both these views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: homeschooling and traditional schooling are competing educational approaches with different strengths. 2. Benefits of homeschooling: flexible pace and schedule, personalized curriculum matching child's interests and learning style, stronger family bonds, safer environment. 3. Benefits of traditional schooling: professional teachers with specialized training, daily social interaction with diverse peers, structured environment promoting discipline and responsibility, exposure to broader experiences and facilities. 4. Own opinion: most children benefit more from structured schools because they provide trained educators, peer interaction, and organized opportunities that most families cannot replicate; homeschooling may be ideal in specific cases. 5. Conclusion: families should choose based on circumstances, but strong public schools remain essential for society.",
        "sample_essay":"The question of whether children should be educated at home or in traditional schools has generated growing debate in recent decades, as families seek alternatives they perceive as better suited to their children's needs. While homeschooling offers genuine flexibility and personalization, I believe that most children benefit more from attending professionally run schools because they provide structured learning, social interaction, and professional expertise that most parents cannot match. Supporters of homeschooling emphasize its flexibility and customization. Parents can adapt the curriculum, pace, and teaching methods to a child's individual strengths, weaknesses, and interests. Children who struggle in traditional classrooms due to learning differences or anxiety may thrive in a supportive home environment with individualized attention. Homeschooling also allows families to integrate education with real-life experiences such as travel, apprenticeships, and community work. In well-designed homeschooling programs, children often show strong academic results and close family bonds. Despite these advantages, traditional schools offer benefits that are difficult to replicate at home. Qualified teachers receive years of professional training in pedagogy and child psychology, enabling them to support diverse learners effectively. Peer interaction in schools teaches children cooperation, communication, conflict resolution, and cultural understanding through daily contact with classmates from different backgrounds. Schools also offer specialized resources such as science laboratories, sports facilities, libraries, music programs, and organized extracurricular activities that are prohibitively expensive for individual families to provide. Furthermore, schools expose children to a structured daily routine and external expectations, preparing them for the discipline and responsibility required at university and in adult working life. In my opinion, homeschooling is an excellent option for some families, particularly when parents have the time, educational background, and dedication required. However, for the majority of children, traditional schools provide a more balanced preparation for adulthood because they combine trained instruction with essential social experiences and resources most families cannot afford to duplicate at home. In conclusion, while homeschooling offers valuable flexibility and personalized learning, traditional schools remain the best educational choice for most children because they provide professional teaching, peer interaction, and organized learning experiences. Rather than viewing them as opposites, families and communities should support both options so that parents can choose what suits their children best."
    },
    {
        "type":"Task2",
        "topic":"Creative arts in education - Advantages outweigh disadvantages?",
        "prompt":"In many education systems, increasing emphasis is placed on academic subjects such as mathematics, science, and language, while creative subjects such as art, music, and drama are reduced or removed from the curriculum. Do the advantages of this trend outweigh the disadvantages? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: academic subjects are increasingly prioritized over creative arts; this trend reflects legitimate economic concerns but sacrifices important educational benefits. 2. Advantages of emphasizing academics: prepares students for university and demanding careers in technology and science, supports national economic competitiveness, focuses limited time on subjects seen as essential. 3. Disadvantages of reducing creative arts: deprives students of emotional development and self-expression, reduces development of creativity and problem solving, lowers motivation and enjoyment of school for non-academically inclined students, weakens cultural transmission. 4. Evaluation: creative arts support rather than undermine academic performance; long-term creative skills increasingly important in modern economy; well-rounded education requires balance. 5. Conclusion: schools should integrate creative subjects into the curriculum as essential components rather than expendable extras.",
        "sample_essay":"In recent years, schools worldwide have increasingly prioritized subjects such as mathematics, science, and languages, while creative arts including music, art, and drama are often reduced or eliminated from the curriculum. This shift reflects economic pressures and the perceived importance of academic skills in a competitive global economy. While strengthening academic subjects offers some real benefits, I believe the long-term disadvantages of reducing creative arts are more significant because creativity, emotional development, and cultural understanding remain essential to individual fulfillment and economic innovation. Focusing on core academic subjects has clear advantages. Strong mathematical, scientific, and linguistic abilities are universally regarded as foundations for university admission and successful careers in technology, medicine, engineering, and finance. Governments often justify emphasizing these subjects by arguing that international economic competitiveness depends on a skilled workforce in scientific and technical fields. Furthermore, schools facing limited time and resources frequently see creative subjects as expendable extras rather than essential learning, especially when external assessments reward academic knowledge. Despite these justifications, reducing creative arts harms students in serious and sometimes unrecognized ways. Art, music, and drama foster creative thinking and innovation by encouraging students to imagine, experiment, and express ideas in original ways. Creative subjects also provide essential outlets for emotional expression and stress relief, helping young people develop resilience and self-understanding. For students whose strengths are non-academic, arts programs may be their primary motivation for attending school, and removing them risks disengagement or dropout. Moreover, creative subjects transmit cultural heritage and build community through shared performances and exhibitions. Modern economies increasingly demand creative problem solving, communication, and collaboration—skills that the arts develop directly. In conclusion, while strengthening core academic skills is important, this should not come at the expense of creative arts. Rather than treating academic and creative subjects as opposites, schools should integrate them to provide balanced education that prepares students both academically and emotionally for adult life. Investing in creative arts education ultimately supports long-term innovation, emotional resilience, and cultural vitality while maintaining the academic foundations necessary for success."
    },
    {
        "type":"Task2",
        "topic":"Consumerism and happiness - Agree or disagree",
        "prompt":"Some people believe that buying and owning more material possessions leads to greater happiness and personal fulfillment. Others argue that true happiness comes from non-material aspects of life such as relationships, experiences, and personal growth. Discuss both these views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: consumer culture promotes material acquisition as a source of happiness, yet evidence suggests non-material factors contribute more to long-term well-being. 2. View favoring material possessions: ownership provides comfort, security, convenience, and social status; possessions such as housing, transportation, and technology improve quality of life materially. 3. View favoring non-material happiness: relationships, meaningful work, health, and experiences bring enduring satisfaction; research shows income above basic needs contributes diminishing happiness returns while experiences provide lasting memories. 4. Own opinion: both material and non-material goods matter, but non-material aspects of life drive lasting happiness; possessions can support but not substitute for relationships and growth. 5. Conclusion: balanced approach valuing possessions as means rather than ends while prioritizing relationships and personal development.",
        "sample_essay":"Modern consumer culture frequently promotes the idea that happiness comes from buying and owning more possessions, yet many people and studies suggest that deeper and more lasting satisfaction derives from non-material aspects of life such as relationships, experiences, and personal growth. This essay will discuss both perspectives and argue that while material goods provide important comfort and security, true happiness and long-term fulfillment depend primarily on non-material foundations. Material possessions undeniably contribute to happiness in practical ways. Adequate housing, reliable transportation, access to technology, and sufficient income reduce stress and improve everyday comfort, creating essential foundations for a satisfying life. Beyond basic comfort, possessions can signal social status, provide a sense of achievement, and offer convenience, helping people live more efficiently. Advertising and social media continually reinforce the message that new products bring satisfaction, and in the short term, acquiring something new genuinely does produce feelings of pleasure and excitement. Despite these immediate pleasures, non-material factors consistently appear more important for long-term happiness in research and personal experience. Strong family relationships, loyal friendships, meaningful work, and personal growth provide enduring satisfaction that material goods rarely sustain. Numerous international studies on happiness demonstrate that once basic needs are met, additional income and possessions contribute very little to long-term well-being. In contrast, shared experiences such as travel, learning, creative projects, and quality time with loved ones generate lasting memories and deepen relationships. Furthermore, excessive focus on material acquisition can paradoxically reduce happiness by fueling dissatisfaction with what one already owns, increasing debt, and consuming time better spent elsewhere. In my view, the most satisfying life balances material comfort with rich non-material experience. Possessions should be valued primarily for their usefulness in supporting meaningful goals and relationships, not as ends in themselves. In conclusion, while material goods contribute essential comfort and convenience, they are rarely sufficient for lasting happiness. True fulfillment depends on cultivating strong relationships, meaningful experiences, and personal growth, with possessions supporting rather than defining a satisfying life. Recognizing this distinction can help individuals make wiser choices about how to spend their time and money in pursuit of genuine long-term well-being."
    },
    {
        "type":"Task2",
        "topic":"Retirement age - Agree or disagree",
        "prompt":"Because of increased life expectancy and financial pressures on pension systems, some people believe that the official age of retirement should be raised significantly for future generations. To what extent do you agree or disagree with this suggestion? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: aging populations create financial pressure on public pension systems; raising retirement age is widely proposed but controversial. 2. Arguments for raising retirement age: longer life expectancy means people can and should work longer; reduces financial burden on shrinking workforce; keeps older people engaged; maintains tax revenues. 3. Arguments against raising retirement age: unfair to people in physically demanding jobs with shorter healthy life expectancy; reduces employment opportunities for young workers; penalizes people who have worked and contributed under existing rules; ignores value of unpaid work retirees perform. 4. Own opinion: a flexible, gradual increase with exceptions for demanding jobs is reasonable; governments should also raise pension contributions, automate savings, and support senior employment rather than relying purely on raising the age. 5. Conclusion: some adjustment may be unavoidable but should be humane and balanced.",
        "sample_essay":"Rising life expectancies combined with falling birth rates have placed public pension systems under growing financial strain worldwide. To ensure sustainability, some policymakers propose significantly raising the official retirement age for future generations. While this suggestion has economic logic, I believe it should be implemented carefully, gradually, and with important exceptions, because a uniform increase would unfairly disadvantage certain groups. The strongest argument for raising the retirement age is demographic: people are living longer and typically enjoy more years of good health than previous generations. With fewer young workers supporting each retiree, leaving the workforce at sixty or sixty-five may become financially unsustainable for pension systems designed decades ago. Delaying retirement by several years would both extend contributions and reduce payouts, helping to preserve public finances while also keeping older workers economically active and socially engaged. Many older adults also report that continuing to work in appropriate roles provides mental stimulation and a sense of purpose. Despite these financial advantages, raising the retirement age significantly raises serious equity concerns. Workers in physically demanding or dangerous jobs may not be able to work productively into their late sixties, and such individuals typically have shorter healthy life expectancies than office workers. Forcing them to retire later may reduce or even eliminate the benefits they have spent a lifetime contributing toward. Additionally, delaying retirement may limit employment opportunities for younger people entering the workforce, particularly in economies with limited job growth. Finally, older people make substantial unrecognized contributions to society through unpaid care work, volunteering, and family support; forcing formal employment longer may reduce these valuable activities. Rather than a single, significant increase applied uniformly, governments should adopt a balanced strategy: gradual, modest increases in the standard retirement age combined with flexible retirement options, exceptions for physically demanding work, and higher savings rates to fund pensions without over-reliance on public budgets. In conclusion, while some adjustment to the retirement age may be necessary for financial sustainability, significant increases should be implemented cautiously and flexibly. A balanced policy that considers health, equity, and economic context will better protect both pension systems and the well-being of all citizens as populations age."
    },
    {
        "type":"Task2",
        "topic":"Social media effects - Causes and effects",
        "prompt":"Social media platforms such as Facebook, Instagram, and Twitter have become central to how many people interact, obtain news, and spend leisure time. What are the main effects of this trend on individuals and society, and are these effects mostly positive or negative? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: social media has become pervasive in daily life, transforming communication, news consumption, and social life with both positive and negative consequences. 2. Positive effects: facilitates connection with friends and family worldwide, enables grassroots social movements, supports businesses and creators, provides access to diverse information and communities. 3. Negative effects: reduces face-to-face interaction and can weaken real-world relationships, contributes to anxiety, depression, and sleep loss through overuse and comparison culture, enables misinformation and political polarization, reduces attention spans, undermines privacy. 4. Evaluation: effects depend on usage patterns; moderate, intentional use offers benefits while compulsive or passive scrolling tends to harm well-being; regulation and better design could improve outcomes. 5. Conclusion: social media is neutral in principle but requires thoughtful use and regulation to maximize benefits and minimize harms.",
        "sample_essay":"The rise of social media platforms has fundamentally reshaped how people communicate, consume news, and spend leisure time within just one generation. While social media has created remarkable opportunities for connection and information sharing, it has also generated serious concerns about mental health, privacy, and social cohesion. Its overall impact is complex and depends heavily on how it is used, though negative effects increasingly dominate public discussion. Social media offers several undeniable benefits. It allows people to maintain relationships across long distances, share life experiences with friends and family, and discover communities with shared interests that may not exist locally. Politically, social media has enabled grassroots movements and citizen journalism, providing channels for marginalized voices that traditional media often ignore. Small businesses and independent creators can reach global audiences at low cost, democratizing access to market opportunities. Furthermore, social platforms distribute educational content and emergency information rapidly, potentially saving lives during natural disasters or health crises. Despite these advantages, research and everyday experience reveal serious negative effects of heavy social media use. Compulsive scrolling and endless streams of curated content reduce attention spans and time available for more demanding activities such as reading or outdoor exercise. Platforms are designed to be addictive and frequently promote harmful comparison cultures in which users feel inadequate comparing their real lives to others' highlight reels. Scientific studies link heavy social media use to increased rates of anxiety, depression, loneliness, and sleep deprivation, particularly among young users. Additionally, social media has become a major conduit for misinformation and political polarization, as algorithms reward outrage and extreme views to maximize engagement, while privacy violations have exposed millions to manipulation. Rather than condemning social media entirely, societies should encourage thoughtful use and demand better platform design and regulation. Users who limit time, engage actively rather than passively, and choose purposeful connections over endless scrolling report greater satisfaction than those who use platforms compulsively. Governments should also enforce privacy protections and require more transparency from social media companies. In conclusion, while social media provides valuable tools for connection, information, and economic opportunity, its current design often promotes unhealthy use and social division. Individuals, designers, and policymakers share responsibility for making digital communication healthier and more constructive in the future."
    },
    {
        "type":"Task2",
        "topic":"Food production and agriculture - Problems and solutions",
        "prompt":"Modern industrial agriculture produces large quantities of food at low prices but has been criticized for environmental damage and potential long-term risks to food security. What are the most serious problems associated with industrial agriculture, and what solutions could make food production more sustainable? Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: industrial agriculture has successfully increased food production but has also created serious environmental and social challenges requiring sustainable alternatives. 2. Problem 1: environmental damage including soil degradation, water pollution, deforestation, and heavy greenhouse gas emissions from livestock and fertilizers. 3. Problem 2: loss of biodiversity through monoculture farming and heavy chemical use threatening ecosystems and long-term agricultural resilience. 4. Problem 3: health risks from pesticide residues and lower nutritional quality in industrially produced food, plus animal welfare concerns. 5. Solutions: promote sustainable practices such as crop rotation, agroforestry, integrated pest management, and organic farming; reduce food waste globally; support small farmers; develop plant-rich diets and alternative proteins. 6. Conclusion: food system transformation is possible and increasingly urgent.",
        "sample_essay":"Industrial agriculture has successfully increased global food production dramatically over the past half century, helping to feed billions at historically low prices. However, this intensive model of farming has also created serious environmental, social, and health challenges that threaten both future food security and ecological stability. Transforming food production toward greater sustainability is technically possible and increasingly urgent. Industrial agriculture generates several interconnected environmental problems. Intensive farming rapidly depletes and degrades soil, reducing its long-term fertility and requiring ever-greater quantities of synthetic fertilizers. Heavy use of pesticides and fertilizers contaminates groundwater, rivers, and coastal ecosystems, creating dead zones and polluting drinking water supplies. Livestock farming, particularly industrial meat production, accounts for a large share of global greenhouse gas emissions, while clearing forests for crops and pasture destroys biodiversity and reduces the planet's capacity to absorb carbon dioxide. Beyond ecological damage, industrial monoculture farming—growing single crops across vast areas—reduces biodiversity and increases vulnerability to disease, pests, and climate shocks, creating systemic risks to long-term food security. There are also human health concerns: pesticide residues in food, reduced nutritional quality in industrially produced crops, and animal welfare issues associated with crowded factory farming conditions. Encouragingly, proven alternative farming practices can address these challenges while maintaining productivity. Sustainable farming methods such as crop rotation, mixed cropping, agroforestry, and integrated pest management reduce chemical dependency and rebuild soil health over time. Organic farming, while potentially lower yielding for some crops, avoids synthetic inputs entirely and supports biodiversity. Reducing food waste, which currently destroys roughly one-third of global production, would dramatically ease pressure to expand farming. Governments should also support smaller-scale farmers through training, research, and fair pricing policies, and should promote dietary shifts toward more plant-rich meals and alternative protein sources that reduce demand for industrial meat. In conclusion, while industrial agriculture has improved access to affordable food, its environmental costs and long-term risks are increasingly serious and unsustainable. Through better agricultural practices, reduced waste, and more thoughtful consumption patterns, societies can transform food production toward systems that are both productive and genuinely sustainable for future generations."
    },
    {
        "type":"Task2",
        "topic":"Tourism and cultural preservation - Discuss both views and own opinion",
        "prompt":"International tourism has grown enormously in recent decades. Some people believe this helps protect traditional cultures, while others argue it leads to the loss of cultural identity and should be limited. Discuss both these views and give your own opinion. Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
        "sample_outline":"1. Introduction: international tourism has grown rapidly; it affects traditional cultures ambivalently, with both protective and destructive consequences. 2. How tourism can protect culture: creates economic incentives for preservation, provides funding for heritage sites, revives traditional crafts and performance, builds cultural pride and awareness. 3. How tourism can damage culture: commercialization and Disneyfication of traditions, overcrowding and physical damage to heritage sites, social disruption from mass tourism, erosion of local lifestyles. 4. Own opinion: well-managed tourism protects and supports culture; poor management destroys it; the solution is thoughtful regulation rather than simple restriction. 5. Conclusion: tourism should be planned with the participation and benefit of local communities to ensure sustainability and respect.",
        "sample_essay":"International tourism has grown exponentially over recent decades, becoming one of the world's largest economic sectors and bringing large numbers of foreign visitors into contact with traditional cultures. While tourism creates opportunities for cultural preservation and mutual understanding, poorly managed mass tourism can also threaten cultural identity and heritage sites. This essay will discuss both perspectives before arguing that thoughtful, community-informed tourism management offers the best path forward. Tourism can powerfully support the preservation of traditional cultures. Visiting foreign sites creates economic incentives for local communities to maintain heritage buildings, traditional crafts, and cultural performances that might otherwise disappear in the pressure of modernization. Tourism revenue has funded the restoration of monuments, the revival of dying traditional arts, and the establishment of cultural museums worldwide. Tourists also frequently develop respect and affection for cultures they experience firsthand, fostering cross-cultural understanding and building political support for cultural protection. Many traditional communities report a renewed sense of pride and interest in their own heritage after discovering that outsiders value it. Despite these benefits, mass tourism can threaten cultural identity. In popular destinations, traditional culture is sometimes reduced to commercialized performances designed for brief entertainment rather than authentic expression, a phenomenon critics describe as Disneyfication. Overcrowding and physical damage threaten fragile heritage sites such as ancient temples or historic city centers. The rapid construction of hotels and tourist infrastructure can also disrupt traditional neighborhoods and raise living costs for local residents, forcing original communities to relocate. Additionally, constant exposure to foreign tourists and consumer culture may gradually erode traditional lifestyles and values, particularly among younger residents. In my view, tourism should be thoughtfully managed rather than simply encouraged or restricted. Successful tourist destinations implement measures such as visitor limits at sensitive sites, revenue sharing with local communities, strict construction regulations, and education programs that inform visitors about cultural respect. When local residents participate in designing tourism policies and receive direct economic benefits, tourism tends to support culture rather than undermine it. In conclusion, while international tourism carries genuine risks to cultural heritage, it can also be a powerful force for preservation if carefully managed. Through regulation, community involvement, and respectful planning, tourism can celebrate cultural diversity while improving the livelihoods of people whose traditions make their destinations valuable in the first place."
    }
]

with open('/workspace/public/data/writing-seed.json','w',encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f"writing-seed.json: {len(data)} items")
