import json

data = [
    {"word":"accommodation","meaning":"n. 住宿；膳宿","category":"Accommodation","example":"I'm looking for affordable accommodation near the university campus."},
    {"word":"landlord","meaning":"n. 房东；地主","category":"Accommodation","example":"The landlord promised to repair the broken window this week."},
    {"word":"tenant","meaning":"n. 房客；承租人","category":"Accommodation","example":"Tenants are required to pay one month's rent in advance."},
    {"word":"deposit","meaning":"n. 押金；存款","category":"Accommodation","example":"You'll need to pay a security deposit before moving in."},
    {"word":"lease","meaning":"n. 租约；租期","category":"Accommodation","example":"The standard lease agreement runs for twelve months."},
    {"word":"reservation","meaning":"n. 预订；预约","category":"Accommodation","example":"Please confirm your reservation by email before arrival."},
    {"word":"dormitory","meaning":"n. 学生宿舍；集体寝室","category":"Accommodation","example":"Most first-year students live in the university dormitories."},
    {"word":"bedsitter","meaning":"n. 卧室兼起居室；单间公寓","category":"Accommodation","example":"She rented a furnished bedsitter near the city center."},
    {"word":"utility","meaning":"n. 公用设施；水电煤","category":"Accommodation","example":"Monthly rent includes all utilities except electricity."},
    {"word":"furnished","meaning":"adj. 带家具的；配备家具的","category":"Accommodation","example":"Furnished apartments are more expensive than unfurnished ones."},
    {"word":"itinerary","meaning":"n. 行程；旅行计划","category":"Travel","example":"Please send me your detailed itinerary for the business trip."},
    {"word":"passport","meaning":"n. 护照；通行证","category":"Travel","example":"You must carry a valid passport when traveling internationally."},
    {"word":"visa","meaning":"n. 签证","category":"Travel","example":"Tourists from certain countries need a visa to enter."},
    {"word":"luggage","meaning":"n. 行李；包裹","category":"Travel","example":"Passengers are limited to two pieces of checked luggage."},
    {"word":"reservation","meaning":"n. 预订；预约","category":"Travel","example":"We have a reservation for two people at seven this evening."},
    {"word":"boarding","meaning":"n. 登机；登船；寄宿","category":"Travel","example":"Boarding for flight CA123 will begin in ten minutes."},
    {"word":"terminal","meaning":"n. 航站楼；终点站；终端","category":"Travel","example":"International flights depart from Terminal Three."},
    {"word":"customs","meaning":"n. 海关；关税；习俗","category":"Travel","example":"All luggage must go through customs inspection."},
    {"word":"platform","meaning":"n. 站台；平台；讲坛","category":"Travel","example":"The train to Oxford arrives at platform five."},
    {"word":"commuter","meaning":"n. 通勤者；月票乘客","category":"Travel","example":"Many commuters take the train into the city every morning."},
    {"word":"enrollment","meaning":"n. 注册；入学；招生人数","category":"Education","example":"Enrollment for new students closes at the end of August."},
    {"word":"curriculum","meaning":"n. 课程；全部课程","category":"Education","example":"The school curriculum emphasizes science and mathematics."},
    {"word":"semester","meaning":"n. 学期；半学年","category":"Education","example":"Students take approximately five courses each semester."},
    {"word":"assignment","meaning":"n. 作业；任务；分配","category":"Education","example":"The history assignment is due next Friday afternoon."},
    {"word":"lecture","meaning":"n./v. 演讲；讲座；讲课","category":"Education","example":"Professor Smith gave an interesting lecture on climate change."},
    {"word":"tutorial","meaning":"n. 辅导课；个别指导","category":"Education","example":"We meet with our tutor once a week for tutorials."},
    {"word":"syllabus","meaning":"n. 教学大纲；课程提纲","category":"Education","example":"The syllabus lists all required readings for the course."},
    {"word":"deadline","meaning":"n. 截止期限；最后期限","category":"Education","example":"Students must submit assignments before the published deadline."},
    {"word":"attendance","meaning":"n. 出席；出勤；参加人数","category":"Education","example":"Regular attendance is required to pass the course."},
    {"word":"scholarship","meaning":"n. 奖学金；学问；学识","category":"Education","example":"She won a full scholarship to study engineering."},
    {"word":"prescription","meaning":"n. 处方；规定；惯例","category":"Health","example":"The doctor gave me a prescription for antibiotics."},
    {"word":"symptom","meaning":"n. 症状；征兆","category":"Health","example":"Common flu symptoms include fever and muscle pain."},
    {"word":"appointment","meaning":"n. 约会；预约；任命","category":"Health","example":"The dentist's appointment is scheduled for next Tuesday."},
    {"word":"diagnosis","meaning":"n. 诊断；诊断结果","category":"Health","example":"Early diagnosis significantly improves treatment outcomes."},
    {"word":"therapy","meaning":"n. 治疗；疗法","category":"Health","example":"Physical therapy helps patients recover after surgery."},
    {"word":"vaccine","meaning":"n. 疫苗","category":"Health","example":"The government recommends annual flu vaccines for elderly people."},
    {"word":"pharmacy","meaning":"n. 药房；制药学；药店","category":"Health","example":"You can collect your medicine from the pharmacy downstairs."},
    {"word":"surgeon","meaning":"n. 外科医生；军医","category":"Health","example":"The surgeon performed a successful heart operation."},
    {"word":"nutrition","meaning":"n. 营养；营养学；食物","category":"Health","example":"Proper nutrition is essential during pregnancy."},
    {"word":"medication","meaning":"n. 药物；药品；药物治疗","category":"Health","example":"Please inform the nurse about your current medications."},
    {"word":"colleague","meaning":"n. 同事；同僚","category":"Work","example":"My colleagues organized a surprise birthday party for me."},
    {"word":"employer","meaning":"n. 雇主；老板","category":"Work","example":"Employers are required to provide safe working conditions."},
    {"word":"employee","meaning":"n. 雇员；员工","category":"Work","example":"The company has over 2,000 employees worldwide."},
    {"word":"interview","meaning":"n./v. 面试；采访；接见","category":"Work","example":"She has a job interview at the finance company tomorrow."},
    {"word":"resume","meaning":"n. 简历；履历","category":"Work","example":"Please submit your resume and cover letter online."},
    {"word":"salary","meaning":"n. 薪水；月薪","category":"Work","example":"Entry-level salaries in this industry are competitive."},
    {"word":"promotion","meaning":"n. 晋升；促销；促进","category":"Work","example":"She received a promotion after just one year with the company."},
    {"word":"colleague","meaning":"n. 同事","category":"Work","example":"Our colleagues from the Paris office are visiting this week."},
    {"word":"contract","meaning":"n. 合同；契约","category":"Work","example":"He signed a two-year contract with the firm."},
    {"word":"overtime","meaning":"n./adj. 加班；超时","category":"Work","example":"Many employees work overtime to finish projects on schedule."},
    {"word":"pollution","meaning":"n. 污染；污染物","category":"Environment","example":"Air pollution in major cities poses serious health risks."},
    {"word":"emission","meaning":"n. 排放；散发；发射","category":"Environment","example":"New regulations aim to reduce carbon emissions by 40%."},
    {"word":"recycle","meaning":"v. 回收利用；使再循环","category":"Environment","example":"Families should recycle paper, glass, and plastic regularly."},
    {"word":"ecosystem","meaning":"n. 生态系统","category":"Environment","example":"Wetlands are valuable ecosystems supporting diverse wildlife."},
    {"word":"deforestation","meaning":"n. 砍伐森林；毁林","category":"Environment","example":"Deforestation threatens many endangered species."},
    {"word":"sustainable","meaning":"adj. 可持续的；能维持的","category":"Environment","example":"Governments promote sustainable development practices."},
    {"word":"biodiversity","meaning":"n. 生物多样性","category":"Environment","example":"The Amazon rainforest contains extraordinary biodiversity."},
    {"word":"conservation","meaning":"n. 保存；保护；节约","category":"Environment","example":"Energy conservation reduces household costs and emissions."},
    {"word":"renewable","meaning":"adj. 可再生的；可更新的","category":"Environment","example":"Renewable energy sources include solar and wind power."},
    {"word":"wildlife","meaning":"n. 野生动植物","category":"Environment","example":"National parks protect wildlife from human disturbance."},
    {"word":"software","meaning":"n. 软件","category":"Technology","example":"New software increases productivity in the workplace."},
    {"word":"hardware","meaning":"n. 硬件；五金器具","category":"Technology","example":"The office upgraded its computer hardware last month."},
    {"word":"database","meaning":"n. 数据库","category":"Technology","example":"Customer information is stored securely in the database."},
    {"word":"algorithm","meaning":"n. 算法；规则系统","category":"Technology","example":"Search engines use complex algorithms to rank results."},
    {"word":"network","meaning":"n./v. 网络；网状系统；联网","category":"Technology","example":"Our office network connects 300 computers across two buildings."},
    {"word":"password","meaning":"n. 密码；口令","category":"Technology","example":"Users should change their passwords regularly for security."},
    {"word":"application","meaning":"n. 应用程序；申请；应用","category":"Technology","example":"Mobile applications have transformed daily banking services."},
    {"word":"interface","meaning":"n. 界面；接口；交接处","category":"Technology","example":"The new user interface is simpler and more intuitive."},
    {"word":"automation","meaning":"n. 自动化；自动操作","category":"Technology","example":"Automation has transformed manufacturing worldwide."},
    {"word":"encryption","meaning":"n. 加密；编码","category":"Technology","example":"Encryption protects personal data during online transactions."},
    {"word":"government","meaning":"n. 政府；政体；管理","category":"Social issues","example":"The government proposed new legislation on housing."},
    {"word":"policy","meaning":"n. 政策；方针；策略","category":"Social issues","example":"Government policies should address affordable housing needs."},
    {"word":"inequality","meaning":"n. 不平等；不平均","category":"Social issues","example":"Economic inequality remains a challenge in many countries."},
    {"word":"immigration","meaning":"n. 移居；移民入境","category":"Social issues","example":"Immigration has shaped cultural diversity in the city."},
    {"word":"infrastructure","meaning":"n. 基础设施；基础结构","category":"Social issues","example":"The country requires investment in public infrastructure."},
    {"word":"population","meaning":"n. 人口；全体居民","category":"Social issues","example":"The country's population is aging rapidly."},
    {"word":"poverty","meaning":"n. 贫困；贫穷；贫乏","category":"Social issues","example":"Government programs aim to reduce childhood poverty."},
    {"word":"democracy","meaning":"n. 民主；民主制度；民主国家","category":"Social issues","example":"Citizens participate in democracy through free elections."},
    {"word":"community","meaning":"n. 社区；团体；共同体","category":"Social issues","example":"Local communities organized charity events this month."},
    {"word":"regulation","meaning":"n. 规章；规则；管理","category":"Social issues","example":"Financial regulations prevent excessive risk-taking by banks."},
    {"word":"receipt","meaning":"n. 收据；收到；收入","category":"Shopping","example":"Always keep your receipt when making a purchase."},
    {"word":"refund","meaning":"n./v. 退款；偿还；归还","category":"Shopping","example":"You can request a full refund within 30 days of purchase."},
    {"word":"discount","meaning":"n./v. 折扣；打折出售","category":"Shopping","example":"Members receive a ten percent discount on all products."},
    {"word":"guarantee","meaning":"n./v. 保证；保证书；担保","category":"Shopping","example":"The product comes with a two-year manufacturer's guarantee."},
    {"word":"payment","meaning":"n. 付款；支付；报酬","category":"Shopping","example":"We accept payment by credit card or bank transfer."},
    {"word":"customer","meaning":"n. 顾客；客户","category":"Shopping","example":"Our customers rate our service highly in satisfaction surveys."},
    {"word":"budget","meaning":"n./adj./v. 预算；预算的；安排","category":"Shopping","example":"Households should plan a budget for monthly expenses."},
    {"word":"luxury","meaning":"n./adj. 奢侈；奢侈品；豪华的","category":"Shopping","example":"Luxury goods are taxed at a higher rate in many countries."},
    {"word":"installment","meaning":"n. 分期付款；部分；一期","category":"Shopping","example":"Customers can pay in monthly installments over one year."},
    {"word":"merchandise","meaning":"n./v. 商品；货物；推销","category":"Shopping","example":"The store sells a wide range of general merchandise."},
    {"word":"ingredient","meaning":"n. 成分；原料；因素","category":"Food and drink","example":"The main ingredients of this dish are vegetables and rice."},
    {"word":"recipe","meaning":"n. 食谱；配方；烹饪法","category":"Food and drink","example":"She followed a traditional recipe from her grandmother."},
    {"word":"restaurant","meaning":"n. 餐馆；饭店","category":"Food and drink","example":"The restaurant is famous for its fresh seafood dishes."},
    {"word":"beverage","meaning":"n. 饮料","category":"Food and drink","example":"The menu offers both alcoholic and non-alcoholic beverages."},
    {"word":"cuisine","meaning":"n. 烹饪；菜肴；厨房","category":"Food and drink","example":"Italian cuisine is popular throughout the world."},
    {"word":"vegetarian","meaning":"n./adj. 素食者；素食的","category":"Food and drink","example":"Many restaurants now offer vegetarian menu options."},
    {"word":"appetizer","meaning":"n. 开胃菜；开胃品","category":"Food and drink","example":"We ordered vegetable soup as an appetizer."},
    {"word":"dessert","meaning":"n. 餐后甜点","category":"Food and drink","example":"The dessert menu includes fruit, cake, and ice cream."},
    {"word":"nutrition","meaning":"n. 营养；营养学","category":"Food and drink","example":"School meals should meet high standards of nutrition."},
    {"word":"menu","meaning":"n. 菜单；菜肴；功能表","category":"Food and drink","example":"Please look at the menu while waiting for your table."},
    {"word":"performance","meaning":"n. 表演；演出；执行；表现","category":"Entertainment","example":"The band gave an amazing live performance last night."},
    {"word":"rehearsal","meaning":"n. 排练；演习；预演","category":"Entertainment","example":"The cast held final rehearsal before opening night."},
    {"word":"exhibition","meaning":"n. 展览；展览会；展览品","category":"Entertainment","example":"The museum's new exhibition attracted thousands of visitors."},
    {"word":"festival","meaning":"n. 节日；庆祝活动；音乐节","category":"Entertainment","example":"The annual music festival draws international artists."},
    {"word":"gallery","meaning":"n. 画廊；美术馆；走廊","category":"Entertainment","example":"Local artists displayed paintings at the community gallery."},
    {"word":"audience","meaning":"n. 观众；听众；读者","category":"Entertainment","example":"The audience applauded loudly at the end of the play."},
    {"word":"cinema","meaning":"n. 电影院；电影艺术","category":"Entertainment","example":"International films shown at the cinema every week."},
    {"word":"concert","meaning":"n. 音乐会；一致；和谐","category":"Entertainment","example":"Tickets for the summer concert sold out within hours."},
    {"word":"venue","meaning":"n. 举办地点；会场；犯罪地点","category":"Entertainment","example":"The venue for the awards ceremony holds 5,000 people."},
    {"word":"celebrity","meaning":"n. 名人；名流；名声","category":"Entertainment","example":"The charity event attracted several local celebrities."}
]

with open('/workspace/public/data/listening-seed.json','w',encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f"listening-seed.json: {len(data)} items")
