#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate IELTS learning data files"""
import json

# ==================== FILE 1: Vocabulary ====================
vocabulary_data = [
    # 高频 High Frequency (120)
    {"word": "abandon", "meaning": "v. 放弃；抛弃", "example": "Many students abandon their healthy habits when exams approach.", "category": "高频"},
    {"word": "ability", "meaning": "n. 能力；才能", "example": "The ability to communicate effectively is crucial in modern society.", "category": "高频"},
    {"word": "academic", "meaning": "adj. 学术的；学院的", "example": "Academic research requires both creativity and rigorous methodology.", "category": "高频"},
    {"word": "accelerate", "meaning": "v. 加速；促进", "example": "Technological advances accelerate the pace of social change.", "category": "高频"},
    {"word": "access", "meaning": "n./v. 访问；接近；使用权", "example": "Everyone should have equal access to quality education.", "category": "高频"},
    {"word": "accommodate", "meaning": "v. 容纳；适应；提供住宿", "example": "The university plans to accommodate more international students.", "category": "高频"},
    {"word": "accomplish", "meaning": "v. 完成；实现", "example": "She accomplished her goal through consistent effort and determination.", "category": "高频"},
    {"word": "accurate", "meaning": "adj. 准确的；精确的", "example": "Accurate data collection is essential for scientific research.", "category": "高频"},
    {"word": "achieve", "meaning": "v. 实现；达到", "example": "Many students achieve academic success through disciplined study habits.", "category": "高频"},
    {"word": "acknowledge", "meaning": "v. 承认；确认；致谢", "example": "Researchers must acknowledge the limitations of their study.", "category": "高频"},
    {"word": "acquire", "meaning": "v. 获得；习得", "example": "Children acquire language skills through interaction with others.", "category": "高频"},
    {"word": "adequate", "meaning": "adj. 足够的；充分的", "example": "Adequate sleep is vital for maintaining good health.", "category": "高频"},
    {"word": "adhere", "meaning": "v. 坚持；粘附；遵守", "example": "Students must adhere to the examination regulations.", "category": "高频"},
    {"word": "advocate", "meaning": "v./n. 提倡；拥护；提倡者", "example": "Many educators advocate a student-centered approach to learning.", "category": "高频"},
    {"word": "affect", "meaning": "v. 影响；感动", "example": "Social media significantly affects how people communicate.", "category": "高频"},
    {"word": "aggregate", "meaning": "n./v./adj. 总计；聚合；总的", "example": "The aggregate data shows a clear upward trend in online learning.", "category": "高频"},
    {"word": "alleviate", "meaning": "v. 减轻；缓解", "example": "Regular exercise can alleviate symptoms of stress and anxiety.", "category": "高频"},
    {"word": "allocate", "meaning": "v. 分配；分派", "example": "Governments must allocate resources efficiently to tackle poverty.", "category": "高频"},
    {"word": "alternative", "meaning": "adj./n. 可选择的；替代物", "example": "Renewable energy provides an alternative to fossil fuels.", "category": "高频"},
    {"word": "ambiguous", "meaning": "adj. 模棱两可的；含糊的", "example": "Ambiguous instructions can lead to misunderstandings in the workplace.", "category": "高频"},
    {"word": "ambitious", "meaning": "adj. 有雄心的；有抱负的", "example": "Ambitious students often set challenging goals for themselves.", "category": "高频"},
    {"word": "analyze", "meaning": "v. 分析；解析", "example": "Researchers analyze complex data sets to identify patterns.", "category": "高频"},
    {"word": "approach", "meaning": "n./v. 方法；途径；接近", "example": "A balanced approach to study yields the best results.", "category": "高频"},
    {"word": "appropriate", "meaning": "adj. 适当的；恰当的", "example": "Choosing appropriate vocabulary is essential in academic writing.", "category": "高频"},
    {"word": "arbitrary", "meaning": "adj. 任意的；武断的", "example": "Arbitrary decisions without evidence undermine trust in leadership.", "category": "高频"},
    {"word": "articulate", "meaning": "v./adj. 清晰表达；善于表达的", "example": "Effective speakers articulate their ideas clearly and confidently.", "category": "高频"},
    {"word": "assess", "meaning": "v. 评估；评价", "example": "Teachers regularly assess student progress through various methods.", "category": "高频"},
    {"word": "assume", "meaning": "v. 假定；承担", "example": "One cannot assume that all students learn at the same pace.", "category": "高频"},
    {"word": "attain", "meaning": "v. 达到；获得", "example": "It takes years of practice to attain proficiency in a second language.", "category": "高频"},
    {"word": "authority", "meaning": "n. 权威；当局；权力", "example": "Educational authorities must address the issue of student well-being.", "category": "高频"},
    {"word": "available", "meaning": "adj. 可利用的；可得到的", "example": "Various online resources are available to support independent learning.", "category": "高频"},
    {"word": "beneficial", "meaning": "adj. 有益的；有利的", "example": "Reading regularly is beneficial for vocabulary development.", "category": "高频"},
    {"word": "bias", "meaning": "n./v. 偏见；使有偏见", "example": "Researchers should avoid personal bias when conducting experiments.", "category": "高频"},
    {"word": "capability", "meaning": "n. 能力；才能；性能", "example": "Modern technology enhances human capability in countless ways.", "category": "高频"},
    {"word": "capacity", "meaning": "n. 容量；能力；产能", "example": "The human brain has an extraordinary capacity for learning.", "category": "高频"},
    {"word": "category", "meaning": "n. 种类；类别；范畴", "example": "Students should organize their notes into clear categories.", "category": "高频"},
    {"word": "cease", "meaning": "v. 停止；终止", "example": "Many traditional industries have ceased to exist due to digitalization.", "category": "高频"},
    {"word": "challenge", "meaning": "n./v. 挑战；向...挑战", "example": "Learning a foreign language presents many intellectual challenges.", "category": "高频"},
    {"word": "channel", "meaning": "n./v. 渠道；频道；引导", "example": "Social media has become a major channel for information dissemination.", "category": "高频"},
    {"word": "circumstance", "meaning": "n. 情况；环境；境况", "example": "Under no circumstances should students plagiarize academic work.", "category": "高频"},
    {"word": "cite", "meaning": "v. 引用；引证；传唤", "example": "Researchers must cite all sources used in their literature review.", "category": "高频"},
    {"word": "clarify", "meaning": "v. 澄清；阐明", "example": "The professor tried to clarify the complex theory with examples.", "category": "高频"},
    {"word": "coherent", "meaning": "adj. 连贯的；一致的；有条理的", "example": "A coherent argument requires logical structure and evidence.", "category": "高频"},
    {"word": "coincide", "meaning": "v. 一致；巧合；同时发生", "example": "The rise in obesity coincides with the popularity of fast food.", "category": "高频"},
    {"word": "collaborate", "meaning": "v. 合作；协作", "example": "Students often collaborate on group projects to share ideas.", "category": "高频"},
    {"word": "commence", "meaning": "v. 开始；着手", "example": "The conference will commence with a keynote speech on climate change.", "category": "高频"},
    {"word": "commodity", "meaning": "n. 商品；日用品；有用之物", "example": "Clean water has become a valuable commodity in many regions.", "category": "高频"},
    {"word": "comparable", "meaning": "adj. 可比较的；比得上的", "example": "Online courses are now comparable in quality to traditional classes.", "category": "高频"},
    {"word": "compatible", "meaning": "adj. 兼容的；相容的", "example": "The software is compatible with most operating systems.", "category": "高频"},
    {"word": "compel", "meaning": "v. 强迫；迫使； compelling adj. 令人信服的", "example": "Economic hardships compel many families to relocate.", "category": "高频"},
    {"word": "compensate", "meaning": "v. 补偿；赔偿；弥补", "example": "Nothing can compensate for the loss of a child's education.", "category": "高频"},
    {"word": "competent", "meaning": "adj. 有能力的；能干的；胜任的", "example": "Competent teachers inspire confidence in their students.", "category": "高频"},
    {"word": "compile", "meaning": "v. 编译；汇编；编写", "example": "She compiled extensive research for her dissertation.", "category": "高频"},
    {"word": "complement", "meaning": "n./v. 补充；补足物；补足", "example": "Theory and practice complement each other in education.", "category": "高频"},
    {"word": "comply", "meaning": "v. 顺从；遵守；应允", "example": "All students must comply with the university's code of conduct.", "category": "高频"},
    {"word": "comprehensive", "meaning": "adj. 全面的；综合的；广泛的", "example": "A comprehensive review of literature strengthens academic papers.", "category": "高频"},
    {"word": "concept", "meaning": "n. 概念；观念；设想", "example": "The concept of sustainable development has gained global attention.", "category": "高频"},
    {"word": "conclude", "meaning": "v. 得出结论；结束；推断", "example": "Researchers conclude that early intervention produces better outcomes.", "category": "高频"},
    {"word": "conduct", "meaning": "v./n. 进行；实施；行为", "example": "Scientists conduct experiments to test their hypotheses.", "category": "高频"},
    {"word": "confer", "meaning": "v. 授予；给予；协商", "example": "The university will confer degrees on over 2,000 graduates this year.", "category": "高频"},
    {"word": "confine", "meaning": "v./n. 限制；禁闭；界限", "example": "Learning should not be confined to the classroom.", "category": "高频"},
    {"word": "confirm", "meaning": "v. 确认；证实；批准", "example": "Further studies confirmed the initial research findings.", "category": "高频"},
    {"word": "conflict", "meaning": "n./v. 冲突；矛盾；抵触", "example": "Work and study commitments often conflict for adult learners.", "category": "高频"},
    {"word": "conform", "meaning": "v. 遵守；符合；遵从", "example": "Children often conform to peer pressure during adolescence.", "category": "高频"},
    {"word": "consensus", "meaning": "n. 一致；共识；舆论", "example": "There is growing consensus that climate action is urgently needed.", "category": "高频"},
    {"word": "consequence", "meaning": "n. 结果；后果；重要性", "example": "Poor dietary choices have serious long-term health consequences.", "category": "高频"},
    {"word": "considerable", "meaning": "adj. 相当大的；值得考虑的", "example": "Considerable progress has been made in renewable energy technology.", "category": "高频"},
    {"word": "constitute", "meaning": "v. 构成；组成；设立", "example": "Women constitute the majority of students in many universities.", "category": "高频"},
    {"word": "constrain", "meaning": "v. 约束；限制；强迫", "example": "Financial constraints limit access to higher education for some.", "category": "高频"},
    {"word": "construct", "meaning": "v./n. 建造；构建；构想", "example": "Students must learn to construct logical arguments in essays.", "category": "高频"},
    {"word": "consult", "meaning": "v. 咨询；商议；查阅", "example": "Patients should consult medical professionals before starting treatment.", "category": "高频"},
    {"word": "consume", "meaning": "v. 消耗；消费；耗尽", "example": "Modern lifestyles consume vast amounts of natural resources.", "category": "高频"},
    {"word": "contemporary", "meaning": "adj./n. 当代的；同时代的；同代人", "example": "Contemporary art reflects the complexities of modern society.", "category": "高频"},
    {"word": "contradict", "meaning": "v. 反驳；与...矛盾；否认", "example": "His actions contradict his stated principles.", "category": "高频"},
    {"word": "contrary", "meaning": "adj./n. 相反的；反面；对立面", "example": "Contrary to popular belief, introverts can excel in leadership roles.", "category": "高频"},
    {"word": "contribute", "meaning": "v. 贡献；捐献；投稿", "example": "Individuals can contribute to environmental protection through daily choices.", "category": "高频"},
    {"word": "controversial", "meaning": "adj. 有争议的；争论的", "example": "Genetic engineering remains a highly controversial topic.", "category": "高频"},
    {"word": "conventional", "meaning": "adj. 传统的；惯例的；常规的", "example": "Conventional teaching methods are being challenged by digital innovation.", "category": "高频"},
    {"word": "convey", "meaning": "v. 传达；运输；表达", "example": "Art can convey emotions that words cannot fully express.", "category": "高频"},
    {"word": "cooperate", "meaning": "v. 合作；配合；协助", "example": "Countries must cooperate to address global environmental challenges.", "category": "高频"},
    {"word": "coordinate", "meaning": "v./adj. 协调；整合；同等的", "example": "Effective leaders coordinate team efforts toward common goals.", "category": "高频"},
    {"word": "core", "meaning": "n./adj. 核心；要点；核心的", "example": "Critical thinking is a core skill in higher education.", "category": "高频"},
    {"word": "correlate", "meaning": "v. 使相互关联；关联", "example": "Studies correlate sleep quality with academic performance.", "category": "高频"},
    {"word": "correspond", "meaning": "v. 符合；对应；通信", "example": "Educational outcomes correspond to levels of student engagement.", "category": "高频"},
    {"word": "credible", "meaning": "adj. 可信的；可靠的；可信任的", "example": "Credible research requires transparent methodology.", "category": "高频"},
    {"word": "critical", "meaning": "adj. 批判的；关键的；批评的", "example": "Early childhood education plays a critical role in development.", "category": "高频"},
    {"word": "crucial", "meaning": "adj. 关键的；决定性的；紧要的", "example": "Vocabulary acquisition is crucial for language learners.", "category": "高频"},
    {"word": "cultivate", "meaning": "v. 培养；耕作；建立", "example": "Parents should cultivate reading habits in children from an early age.", "category": "高频"},
    {"word": "cumbersome", "meaning": "adj. 笨重的；累赘的；麻烦的", "example": "Traditional paper-based systems are increasingly cumbersome.", "category": "高频"},
    {"word": "curriculum", "meaning": "n. 课程；全部课程", "example": "The school curriculum should balance academic and practical skills.", "category": "高频"},
    {"word": "decline", "meaning": "v./n. 下降；衰退；拒绝", "example": "There has been a steady decline in the number of traditional bookstores.", "category": "高频"},
    {"word": "dedicate", "meaning": "v. 致力；奉献；把...用于", "example": "She dedicated herself to the study of environmental science.", "category": "高频"},
    {"word": "deduce", "meaning": "v. 推断；演绎；推论", "example": "From the data, researchers deduced a significant correlation.", "category": "高频"},
    {"word": "defect", "meaning": "n./v. 缺陷；缺点；叛逃", "example": "Genetic defects can cause various health conditions.", "category": "高频"},
    {"word": "define", "meaning": "v. 定义；规定；使明确", "example": "It is important to define key terms at the beginning of an essay.", "category": "高频"},
    {"word": "deliberate", "meaning": "adj./v. 故意的；深思熟虑的；仔细考虑", "example": "Language learning requires deliberate practice and patience.", "category": "高频"},
    {"word": "demonstrate", "meaning": "v. 证明；演示；展示", "example": "The graphs demonstrate a significant increase in global temperatures.", "category": "高频"},
    {"word": "denote", "meaning": "v. 表示；指示；意味着", "example": "In academic writing, certain phrases denote a shift in argument.", "category": "高频"},
    {"word": "depict", "meaning": "v. 描述；描写；描绘", "example": "The chart depicts changes in population over the past century.", "category": "高频"},
    {"word": "derive", "meaning": "v. 得到；源于；导出", "example": "Many English words derive from Latin and Greek roots.", "category": "高频"},
    {"word": "design", "meaning": "n./v. 设计；图案；计划", "example": "Teachers carefully design lessons to maximize student engagement.", "category": "高频"},
    {"word": "designate", "meaning": "v. 指定；指派；标明", "example": "Certain areas are designated as protected wildlife reserves.", "category": "高频"},
    {"word": "despise", "meaning": "v. 鄙视；看不起；厌恶", "example": "He despised dishonesty in any form of academic work.", "category": "高频"},
    {"word": "detect", "meaning": "v. 察觉；发现；探测", "example": "Early screening can detect many diseases before symptoms appear.", "category": "高频"},
    {"word": "determine", "meaning": "v. 决定；确定；测定", "example": "Many factors determine success in language acquisition.", "category": "高频"},
    {"word": "detrimental", "meaning": "adj. 有害的；不利的", "example": "Excessive screen time is detrimental to children's development.", "category": "高频"},
    {"word": "develop", "meaning": "v. 发展；开发；研制", "example": "Universities develop partnerships with industry to promote innovation.", "category": "高频"},
    {"word": "devise", "meaning": "v. 设计；发明；想出", "example": "Researchers devised a new method for data analysis.", "category": "高频"},
    {"word": "diagnose", "meaning": "v. 诊断；判断；断定", "example": "Medical professionals diagnose illnesses based on symptoms and tests.", "category": "高频"},
    {"word": "diminish", "meaning": "v. 减少；降低；削弱", "example": "Traditional values have diminished in modern, fast-paced societies.", "category": "高频"},
    {"word": "discipline", "meaning": "n./v. 纪律；学科；训练；惩罚", "example": "Self-discipline is essential for achieving long-term goals.", "category": "高频"},
    {"word": "disclose", "meaning": "v. 透露；公开；揭发", "example": "Companies must disclose financial information to investors.", "category": "高频"},
    {"word": "discrete", "meaning": "adj. 离散的；分立的；不连续的", "example": "The course breaks down complex topics into discrete modules.", "category": "高频"},
    {"word": "discriminate", "meaning": "v. 歧视；区别；辨别", "example": "Laws prohibit employers from discriminating based on age or gender.", "category": "高频"},
    {"word": "dismiss", "meaning": "v. 解散；解雇；不予考虑", "example": "One should not dismiss alternative perspectives without consideration.", "category": "高频"},
    {"word": "disorder", "meaning": "n. 混乱；骚乱；失调；疾病", "example": "Sleep disorders can seriously affect academic performance.", "category": "高频"},
    {"word": "disperse", "meaning": "v. 驱散；散开；分散", "example": "The crowd dispersed quickly when the police arrived.", "category": "高频"},
    {"word": "displace", "meaning": "v. 取代；移置；迫使离开", "example": "Automation may displace workers in certain industries.", "category": "高频"},
    {"word": "display", "meaning": "n./v. 显示；展览；表现", "example": "The museum displays artifacts from ancient civilizations.", "category": "高频"},
    {"word": "dispose", "meaning": "v. 处理；处置；安排", "example": "Cities must find sustainable ways to dispose of waste.", "category": "高频"},
    {"word": "distinct", "meaning": "adj. 明显的；独特的；清楚的", "example": "Each academic discipline has its own distinct methodology.", "category": "高频"},
    {"word": "distribute", "meaning": "v. 分配；散布；分发", "example": "Governments distribute vaccines equitably across the population.", "category": "高频"},
    {"word": "diverge", "meaning": "v. 分歧；偏离；发散", "example": "Opinions diverge widely on the issue of nuclear energy.", "category": "高频"},
    {"word": "dominate", "meaning": "v. 支配；控制；占优势", "example": "A few large corporations dominate the global tech industry.", "category": "高频"},
    {"word": "dramatic", "meaning": "adj. 戏剧性的；引人注目的；急剧的", "example": "There have been dramatic changes in communication technology.", "category": "高频"},
    {"word": "drastic", "meaning": "adj. 激烈的；猛烈的；极端的", "example": "Drastic measures may be needed to reverse environmental damage.", "category": "高频"},
    {"word": "duplicate", "meaning": "adj./v./n. 复制的；完全相同的；复制；副本", "example": "Students must not submit duplicate work for assessment.", "category": "高频"},
    {"word": "dynamic", "meaning": "adj. 动态的；有活力的；动力的", "example": "Modern cities are dynamic centers of culture and innovation.", "category": "高频"},

    # 学术 Academic (80)
    {"word": "economy", "meaning": "n. 经济；节约；经济制度", "example": "A stable economy provides opportunities for employment and growth.", "category": "学术"},
    {"word": "eliminate", "meaning": "v. 消除；排除；淘汰", "example": "The goal is to eliminate preventable diseases through vaccination.", "category": "学术"},
    {"word": "emerge", "meaning": "v. 出现；浮现；兴起", "example": "New technologies emerge continuously, reshaping our daily lives.", "category": "学术"},
    {"word": "emphasize", "meaning": "v. 强调；着重；使突出", "example": "Educators emphasize the importance of critical thinking skills.", "category": "学术"},
    {"word": "encounter", "meaning": "v./n. 遭遇；遇到；邂逅", "example": "Students often encounter difficulties when transitioning to university.", "category": "学术"},
    {"word": "enforce", "meaning": "v. 实施；执行；强迫", "example": "Schools enforce policies to maintain a safe learning environment.", "category": "学术"},
    {"word": "enhance", "meaning": "v. 提高；增强；改善", "example": "Interactive software can enhance the language learning experience.", "category": "学术"},
    {"word": "enormous", "meaning": "adj. 巨大的；庞大的；极大的", "example": "The growth of online learning has been enormous in recent years.", "category": "学术"},
    {"word": "ensure", "meaning": "v. 保证；确保；担保", "example": "Governments must ensure equal access to quality healthcare.", "category": "学术"},
    {"word": "entail", "meaning": "v. 需要；使必要；牵涉", "example": "Academic research entails meticulous attention to detail.", "category": "学术"},
    {"word": "entity", "meaning": "n. 实体；存在；统一体", "example": "The university operates as an independent legal entity.", "category": "学术"},
    {"word": "environment", "meaning": "n. 环境；周围状况；自然环境", "example": "Protecting the environment requires collective global action.", "category": "学术"},
    {"word": "equivalent", "meaning": "adj./n. 等价的；相等的；等价物", "example": "A diploma is not always equivalent to practical competence.", "category": "学术"},
    {"word": "evolve", "meaning": "v. 进化；发展；逐步演变", "example": "Languages evolve continuously through cultural contact and usage.", "category": "学术"},
    {"word": "exaggerate", "meaning": "v. 夸大；夸张；使过大", "example": "Media reports sometimes exaggerate the risks of certain technologies.", "category": "学术"},
    {"word": "exceed", "meaning": "v. 超过；胜过；越出", "example": "The project exceeded its budget by over 30 percent.", "category": "学术"},
    {"word": "exclude", "meaning": "v. 排除；排斥；不包括", "example": "No student should be excluded from education due to financial status.", "category": "学术"},
    {"word": "execute", "meaning": "v. 执行；实施；处决；完成", "example": "It is one thing to plan, another to execute effectively.", "category": "学术"},
    {"word": "exempt", "meaning": "adj./v. 被免除的；豁免；免除", "example": "Certain charitable organizations are exempt from taxation.", "category": "学术"},
    {"word": "exhaust", "meaning": "v./n. 耗尽；使精疲力竭；废气", "example": "Vehicle exhaust contributes significantly to urban air pollution.", "category": "学术"},
    {"word": "exhibit", "meaning": "v./n. 显示；展出；展览品", "example": "Successful learners exhibit curiosity and persistence.", "category": "学术"},
    {"word": "expand", "meaning": "v. 扩大；扩展；膨胀", "example": "Many universities expand their online course offerings.", "category": "学术"},
    {"word": "explicit", "meaning": "adj. 明确的；清楚的；直率的", "example": "Assignment instructions should be explicit to avoid confusion.", "category": "学术"},
    {"word": "exploit", "meaning": "v. 利用；开发；剥削", "example": "Developing nations must exploit natural resources responsibly.", "category": "学术"},
    {"word": "explore", "meaning": "v. 探索；探究；勘探", "example": "Students are encouraged to explore diverse academic disciplines.", "category": "学术"},
    {"word": "extend", "meaning": "v. 延伸；延长；扩展", "example": "The government extended the deadline for policy consultation.", "category": "学术"},
    {"word": "external", "meaning": "adj. 外部的；外面的；外来的", "example": "Students must balance internal motivation with external pressures.", "category": "学术"},
    {"word": "extract", "meaning": "v./n. 提取；摘录；榨取；提取物", "example": "Researchers extract meaningful patterns from large datasets.", "category": "学术"},
    {"word": "facilitate", "meaning": "v. 促进；使容易；帮助", "example": "Technology facilitates communication across geographical distances.", "category": "学术"},
    {"word": "factor", "meaning": "n./v. 因素；要素；把...因素包括进去", "example": "Economic factors strongly influence educational policy decisions.", "category": "学术"},
    {"word": "faculty", "meaning": "n. 全体教员；能力；学院；系", "example": "The university attracts faculty members from around the world.", "category": "学术"},
    {"word": "feasible", "meaning": "adj. 可行的；可能的；可实行的", "example": "Renewable energy is now economically feasible in most countries.", "category": "学术"},
    {"word": "feature", "meaning": "n./v. 特征；特色；特写；以...为特色", "example": "The new curriculum features courses on digital literacy.", "category": "学术"},
    {"word": "figure", "meaning": "n./v. 数字；图形；人物；计算；认为", "example": "Government figures indicate rising unemployment among youth.", "category": "学术"},
    {"word": "finance", "meaning": "n./v. 财政；金融；经费；为...提供资金", "example": "Many students work part-time to finance their education.", "category": "学术"},
    {"word": "fluctuate", "meaning": "v. 波动；起伏；动摇", "example": "Oil prices fluctuate depending on global economic conditions.", "category": "学术"},
    {"word": "focus", "meaning": "v./n. 集中；聚焦；焦点；重点", "example": "The report focuses on the social impacts of urbanization.", "category": "学术"},
    {"word": "format", "meaning": "n./v. 格式；版式；设计；安排", "example": "Essays must follow the academic format specified in guidelines.", "category": "学术"},
    {"word": "formulate", "meaning": "v. 制定；规划；明确表达", "example": "Researchers formulate hypotheses before conducting experiments.", "category": "学术"},
    {"word": "foundation", "meaning": "n. 基础；根本；基金会；创立", "example": "Early childhood education lays the foundation for lifelong learning.", "category": "学术"},
    {"word": "fraction", "meaning": "n. 分数；小数；部分；片段", "example": "Only a fraction of applicants succeed in gaining admission.", "category": "学术"},
    {"word": "fragment", "meaning": "n./v. 碎片；片段；使分裂；成碎片", "example": "Digital media often presents information in fragmented form.", "category": "学术"},
    {"word": "framework", "meaning": "n. 框架；结构；准则；体系", "example": "The study proposes a framework for understanding cultural change.", "category": "学术"},
    {"word": "fulfill", "meaning": "v. 履行；满足；实现；完成", "example": "Education helps individuals fulfill their personal potential.", "category": "学术"},
    {"word": "function", "meaning": "n./v. 功能；作用；职责；运行；行使职责", "example": "Libraries function as important community learning centers.", "category": "学术"},
    {"word": "fundamental", "meaning": "adj./n. 基本的；根本的；基础；基本原理", "example": "Freedom of expression is a fundamental human right.", "category": "学术"},
    {"word": "generate", "meaning": "v. 产生；发生；生成；引起", "example": "Wind turbines generate electricity without producing carbon emissions.", "category": "学术"},
    {"word": "genuine", "meaning": "adj. 真正的；真诚的；名副其实的", "example": "Genuine academic curiosity drives meaningful research.", "category": "学术"},
    {"word": "global", "meaning": "adj. 全球的；全世界的；总的", "example": "Climate change poses a global challenge requiring collective action.", "category": "学术"},
    {"word": "govern", "meaning": "v. 统治；管理；支配；控制", "example": "Clear principles govern ethical research practices.", "category": "学术"},
    {"word": "gradual", "meaning": "adj. 逐渐的；渐进的；平缓的", "example": "Language proficiency develops through gradual, consistent effort.", "category": "学术"},
    {"word": "guarantee", "meaning": "v./n. 保证；担保；保证书；抵押品", "example": "A university degree does not guarantee employment success.", "category": "学术"},
    {"word": "hence", "meaning": "adv. 因此；所以；今后", "example": "Demand for skilled workers is rising; hence vocational training is critical.", "category": "学术"},
    {"word": "hierarchy", "meaning": "n. 等级制度；层级；层次结构", "example": "Traditional universities often have complex administrative hierarchies.", "category": "学术"},
    {"word": "highlight", "meaning": "v./n. 强调；突出；最精彩部分", "example": "The study highlights disparities in educational attainment.", "category": "学术"},
    {"word": "hypothesis", "meaning": "n. 假设；假说；前提", "example": "Researchers test hypotheses through carefully designed experiments.", "category": "学术"},
    {"word": "identical", "meaning": "adj. 同一的；完全相同的", "example": "No two learning experiences are ever completely identical.", "category": "学术"},
    {"word": "identify", "meaning": "v. 识别；认出；鉴定；确定", "example": "Teachers must identify individual learning needs and adapt accordingly.", "category": "学术"},
    {"word": "ideology", "meaning": "n. 意识形态；思想体系；观念学", "example": "Different political ideologies shape approaches to social welfare.", "category": "学术"},
    {"word": "ignore", "meaning": "v. 忽视；不理；不顾", "example": "Policymakers cannot ignore the long-term costs of environmental damage.", "category": "学术"},
    {"word": "illustrate", "meaning": "v. 说明；阐明；举例说明；插图说明", "example": "Statistics illustrate the scale of the housing affordability problem.", "category": "学术"},
    {"word": "immense", "meaning": "adj. 巨大的；广大的；无限的", "example": "The internet contains immense amounts of information of varying quality.", "category": "学术"},
    {"word": "impact", "meaning": "n./v. 影响；冲击；作用；对...产生影响", "example": "Automation will profoundly impact the future of work.", "category": "学术"},
    {"word": "implement", "meaning": "v./n. 执行；实施；落实；工具；器具", "example": "Governments must implement policies to combat climate change.", "category": "学术"},
    {"word": "implication", "meaning": "n. 含义；暗示；牵连；可能的影响", "example": "The findings have important implications for educational policy.", "category": "学术"},
    {"word": "impose", "meaning": "v. 强加；征收；利用；欺骗", "example": "Authorities sometimes impose restrictions to protect public safety.", "category": "学术"},
    {"word": "incentive", "meaning": "n. 激励；刺激；动机", "example": "Financial incentives can encourage businesses to reduce pollution.", "category": "学术"},
    {"word": "incident", "meaning": "n. 事件；事变；插曲 adj. 附带的", "example": "Safety incidents in laboratories can have serious consequences.", "category": "学术"},
    {"word": "indicate", "meaning": "v. 表明；指示；指出；象征", "example": "Research indicates that exercise improves cognitive function.", "example": "The evidence indicates a strong correlation between the two variables.", "category": "学术"},
    {"word": "individual", "meaning": "n./adj. 个人；个体；单独的；独特的", "example": "Each individual learns differently and at a different pace.", "category": "学术"},
    {"word": "induce", "meaning": "v. 引诱；引起；导致；归纳", "example": "Stress can induce physical symptoms such as headaches and fatigue.", "category": "学术"},
    {"word": "inevitable", "meaning": "adj. 不可避免的；必然发生的", "example": "Change is inevitable in rapidly developing societies.", "category": "学术"},
    {"word": "influence", "meaning": "n./v. 影响；作用；势力；感化；对...起作用", "example": "Family background continues to influence educational outcomes.", "category": "学术"},
    {"word": "inherent", "meaning": "adj. 固有的；内在的；与生俱来的", "example": "The inherent complexity of language makes second-language learning challenging.", "category": "学术"},
    {"word": "initiate", "meaning": "v. 开始；创始；发起；接纳新成员", "example": "Governments initiate programs to support disadvantaged communities.", "category": "学术"},
    {"word": "innovate", "meaning": "v. 创新；改革；引入新事物", "example": "Companies must innovate continuously to remain competitive.", "category": "学术"},
    {"word": "insight", "meaning": "n. 洞察力；洞悉；深刻见解", "example": "The study provides valuable insight into early childhood development.", "category": "学术"},
    {"word": "inspect", "meaning": "v. 检查；视察；审查；审视", "example": "Officials regularly inspect facilities to ensure compliance with safety standards.", "category": "学术"},
    {"word": "inspire", "meaning": "v. 激发；鼓舞；启示；产生", "example": "Great teachers inspire students to pursue knowledge beyond textbooks.", "category": "学术"},
    {"word": "install", "meaning": "v. 安装；设置；任命；安顿", "example": "Schools install security cameras to monitor campus safety.", "category": "学术"},
    {"word": "institute", "meaning": "n./v. 学会；协会；机构；学院；建立；制定；开始", "example": "The institute conducts research on sustainable development.", "category": "学术"},
    {"word": "integrity", "meaning": "n. 正直；诚实；完整性；完全", "example": "Academic integrity is the foundation of scholarly work.", "category": "学术"},
    {"word": "intense", "meaning": "adj. 强烈的；紧张的；热情的", "example": "Intense study sessions are most productive when followed by rest.", "category": "学术"},
    {"word": "interpret", "meaning": "v. 解释；说明；口译；把...理解为", "example": "Researchers interpret data within the context of existing knowledge.", "category": "学术"},
    {"word": "intervene", "meaning": "v. 干预；干涉；介入；插嘴", "example": "Early intervention programs help children with learning difficulties.", "category": "学术"},
    {"word": "intimate", "meaning": "adj./v. 亲密的；私人的；暗示；宣布", "example": "Students need intimate knowledge of grammar to write academically.", "category": "学术"},
    {"word": "intrinsic", "meaning": "adj. 固有的；内在的；本质的", "example": "The intrinsic value of education extends beyond career preparation.", "category": "学术"},
]

# Continue with more academic entries and other categories
additional_vocabulary = [
    {"word": "invalid", "meaning": "adj. 无效的；有病的；残废的", "example": "Arguments based on false assumptions are logically invalid.", "category": "学术"},
    {"word": "invariably", "meaning": "adv. 不变地；总是；始终如一地", "example": "Successful students invariably maintain consistent study routines.", "category": "学术"},
    {"word": "investigate", "meaning": "v. 调查；研究；审查", "example": "Scientists investigate natural phenomena to understand underlying principles.", "category": "学术"},
    {"word": "invoke", "meaning": "v. 引用；唤起；恳求；实施", "example": "Writers often invoke historical examples to strengthen arguments.", "category": "学术"},
    {"word": "isolate", "meaning": "v. 隔离；孤立；使脱离", "example": "Students sometimes isolate themselves socially during exam periods.", "category": "学术"},
    {"word": "issue", "meaning": "n./v. 问题；议题；发行物；发行；发布", "example": "Climate change remains one of the most pressing issues of our time.", "category": "学术"},
    {"word": "justify", "meaning": "v. 证明...正当；为...辩护；调整版面", "example": "Students must justify their claims with evidence and reasoning.", "category": "学术"},
    {"word": "legitimate", "meaning": "adj./v. 合法的；正当的；使合法", "example": "There are legitimate concerns about privacy in the digital age.", "category": "学术"},
    {"word": "leverage", "meaning": "n./v. 杠杆作用；力量；手段；利用；举债经营", "example": "Successful organizations leverage technology to improve efficiency.", "category": "学术"},
    {"word": "liberal", "meaning": "adj./n. 自由的；开明的；慷慨的；自由主义者", "example": "Liberal arts education develops broad intellectual capabilities.", "category": "学术"},
    {"word": "license", "meaning": "n./v. 执照；许可证；许可；批准", "example": "Institutions must obtain proper licenses before offering programs.", "category": "学术"},
    {"word": "limit", "meaning": "n./v. 限制；限度；界限；限定", "example": "Students must learn to manage time within the limits of deadlines.", "category": "学术"},
    {"word": "logical", "meaning": "adj. 逻辑的；合逻辑的；合理的", "example": "Academic essays require clear structure and logical argumentation.", "category": "学术"},
    {"word": "maintain", "meaning": "v. 维持；保持；维护；主张", "example": "Students should maintain a balanced lifestyle for optimal performance.", "category": "学术"},
    {"word": "manipulate", "meaning": "v. 操纵；操作；处理；篡改", "example": "Statistical data can be manipulated to support different conclusions.", "category": "学术"},
    {"word": "manual", "meaning": "n./adj. 手册；说明书；手工的；体力的", "example": "Manual labor has increasingly been replaced by automation.", "category": "学术"},
    {"word": "margin", "meaning": "n. 边缘；利润；页边空白；余地", "example": "The profit margin in traditional publishing has decreased significantly.", "category": "学术"},
    {"word": "massive", "meaning": "adj. 巨大的；大量的；魁伟的", "example": "Massive investment in infrastructure boosts economic development.", "category": "学术"},
    {"word": "mature", "meaning": "adj./v. 成熟的；成年人的；到期的；成熟", "example": "University education helps students mature intellectually and personally.", "category": "学术"},
    {"word": "maximum", "meaning": "n./adj. 最大量；最大限度；最大的", "example": "Students should strive for maximum engagement during lectures.", "category": "学术"},
    {"word": "mechanism", "meaning": "n. 机械装置；机制；机能；途径", "example": "The brain's memory mechanism is not yet fully understood.", "category": "学术"},
    {"word": "medium", "meaning": "n./adj. 媒介；手段；中间；中等的", "example": "Television remains an influential medium of mass communication.", "category": "学术"},
    {"word": "mental", "meaning": "adj. 精神的；脑力的；精神病的", "example": "Universities increasingly recognize the importance of mental health.", "category": "学术"},
    {"word": "merely", "meaning": "adv. 仅仅；只不过；只是", "example": "Education is not merely about memorization, but about understanding.", "category": "学术"},
    {"word": "merge", "meaning": "v. 合并；融入；混合", "example": "Some universities merge departments to encourage interdisciplinary research.", "category": "学术"},
    {"word": "method", "meaning": "n. 方法；方式；秩序；条理", "example": "Different learning methods suit different types of learners.", "category": "学术"},
    {"word": "minimum", "meaning": "n./adj. 最小量；最低限度；最小的", "example": "Universities set minimum entry requirements for academic programs.", "category": "学术"},
    {"word": "minor", "meaning": "adj./n. 较小的；次要的；未成年人；副修科目", "example": "Some stress during exams is normal and usually a minor concern.", "category": "学术"},
    {"word": "misconception", "meaning": "n. 误解；错误观念；错误印象", "example": "There are many misconceptions about how languages are learned.", "category": "学术"},
    {"word": "modify", "meaning": "v. 修改；改变；修饰；缓和", "example": "Teachers modify lesson plans based on student feedback.", "category": "学术"},
    {"word": "monitor", "meaning": "v./n. 监控；监视；监听；监视器；班长", "example": "Researchers monitor participants' progress throughout the study.", "category": "学术"},
    {"word": "motivate", "meaning": "v. 激励；激发...的积极性；成为...的动机", "example": "Intrinsically motivated students tend to achieve better long-term results.", "category": "学术"},
    {"word": "mutual", "meaning": "adj. 相互的；彼此的；共同的", "example": "Mutual respect between teachers and students fosters better learning.", "category": "学术"},
    {"word": "narrow", "meaning": "adj./v. 狭窄的；狭隘的；有限的；缩小", "example": "Students should narrow their research focus before writing a thesis.", "category": "学术"},
    {"word": "negative", "meaning": "adj./n. 消极的；负面的；否定的；否定；底片", "example": "Negative feedback, when constructive, helps students improve.", "category": "学术"},
    {"word": "negligible", "meaning": "adj. 微不足道的；可忽略的；不重要的", "example": "For most students, test anxiety has a negligible effect on scores.", "category": "学术"},
    {"word": "nevertheless", "meaning": "adv./conj. 然而；不过；尽管如此", "example": "Online learning has limitations; nevertheless, it benefits millions.", "category": "学术"},
    {"word": "norm", "meaning": "n. 规范；标准；平均数；准则", "example": "Academic norms vary across different cultural contexts.", "category": "学术"},
    {"word": "notable", "meaning": "adj./n. 显著的；著名的；值得注意的；名人", "example": "Notable scholars often present at international academic conferences.", "category": "学术"},
    {"word": "notion", "meaning": "n. 概念；观念；想法；打算", "example": "The notion that intelligence is fixed has been largely discredited.", "category": "学术"},
    {"word": "notwithstanding", "meaning": "prep./adv./conj. 尽管；虽然；然而", "example": "Notwithstanding the challenges, education remains a powerful tool for change.", "category": "学术"},
    {"word": "novel", "meaning": "adj./n. 新奇的；新颖的；小说", "example": "Novel approaches to teaching can significantly improve student engagement.", "category": "学术"},
    {"word": "numerous", "meaning": "adj. 许多的；众多的；为数众多的", "example": "Numerous studies confirm the value of active learning strategies.", "category": "学术"},

    # 写作 Writing (80)
    {"word": "objective", "meaning": "n./adj. 目标；目的；客观的；无偏见的", "example": "Academic writing requires an objective and evidence-based approach.", "category": "写作"},
    {"word": "observe", "meaning": "v. 观察；注意到；遵守；评论", "example": "Researchers observe patterns in behavior under controlled conditions.", "category": "写作"},
    {"word": "obvious", "meaning": "adj. 明显的；显而易见的；平淡无奇的", "example": "It is obvious that technology has transformed communication patterns.", "category": "写作"},
    {"word": "occasion", "meaning": "n./v. 时机；场合；盛会；引起；惹起", "example": "On occasion, students may need additional support with difficult concepts.", "category": "写作"},
    {"word": "occur", "meaning": "v. 发生；出现；存在；被想到", "example": "Similar problems occur in many developing countries.", "category": "写作"},
    {"word": "odd", "meaning": "adj. 奇怪的；古怪的；奇数的；临时的", "example": "The data showed some odd patterns requiring further investigation.", "category": "写作"},
    {"word": "offset", "meaning": "v./n. 抵消；补偿；弥补；偏移", "example": "Renewable energy can offset emissions from traditional power sources.", "category": "写作"},
    {"word": "ongoing", "meaning": "adj. 进行中的；不断的；持续存在的", "example": "Climate change is an ongoing threat to coastal communities.", "category": "写作"},
    {"word": "operate", "meaning": "v. 运转；操作；经营；动手术", "example": "Governments must operate within legal and ethical boundaries.", "category": "写作"},
    {"word": "optimal", "meaning": "adj. 最佳的；最优的；最适宜的", "example": "Optimal learning conditions include adequate rest and nutrition.", "category": "写作"},
    {"word": "optimum", "meaning": "n./adj. 最佳效果；最佳条件；最佳的", "example": "The optimum temperature for learning varies among individuals.", "category": "写作"},
    {"word": "option", "meaning": "n. 选项；选择权；取舍", "example": "Students should be given options for demonstrating their knowledge.", "category": "写作"},
    {"word": "organize", "meaning": "v. 组织；整理；安排；筹备", "example": "Writers must organize their ideas logically for maximum clarity.", "category": "写作"},
    {"word": "orient", "meaning": "v./n. 使适应；确定方向；使熟悉情况", "example": "Education should orient students toward lifelong learning.", "category": "写作"},
    {"word": "outcome", "meaning": "n. 结果；成果；后果", "example": "Educational outcomes depend on multiple interrelated factors.", "category": "写作"},
    {"word": "overlook", "meaning": "v./n. 俯瞰；忽视；忽略；眺望", "example": "Policymakers often overlook the social determinants of health.", "category": "写作"},
    {"word": "overall", "meaning": "adj./adv./n. 总体的；全面的；大体上；工装裤", "example": "Overall, the benefits of education far outweigh the costs.", "category": "写作"},
    {"word": "overwhelming", "meaning": "adj. 压倒性的；巨大的；无法抵抗的", "example": "The overwhelming majority of students value feedback from teachers.", "category": "写作"},
    {"word": "pace", "meaning": "n./v. 步速；节奏；速度；踱步；调整节奏", "example": "The fast pace of modern life can affect mental well-being.", "category": "写作"},
    {"word": "panel", "meaning": "n./v. 面板；仪表盘；陪审团；专门小组；镶嵌", "example": "A panel of experts reviewed the research methodology.", "category": "写作"},
    {"word": "paradigm", "meaning": "n. 范例；典范；范式；示例", "example": "Digital technology represents a paradigm shift in education.", "category": "写作"},
    {"word": "paradox", "meaning": "n. 悖论；矛盾的人或事；反论", "example": "It is a paradox that increased connectivity can lead to loneliness.", "category": "写作"},
    {"word": "parallel", "meaning": "adj./n./v. 平行的；相同的；平行线；对比", "example": "There are interesting parallels between language and music learning.", "category": "写作"},
    {"word": "participate", "meaning": "v. 参与；参加；分享；分担", "example": "Students who participate actively in class learn more effectively.", "category": "写作"},
    {"word": "passive", "meaning": "adj./n. 被动的；消极的；被动语态的；被动语态", "example": "Passive learning through lectures alone is often insufficient.", "category": "写作"},
    {"word": "perceive", "meaning": "v. 察觉；感知；认为；理解", "example": "Individuals perceive the same information differently based on experience.", "category": "写作"},
    {"word": "permanent", "meaning": "adj. 永久的；固定的；长期的；常设的", "example": "Education has permanent effects on individuals and societies.", "category": "写作"},
    {"word": "persist", "meaning": "v. 坚持；持续；存留；继续存在", "example": "Challenges persist despite improvements in educational technology.", "category": "写作"},
    {"word": "phenomenon", "meaning": "n. 现象；奇迹；杰出的人；非凡的人", "example": "Globalization is a complex phenomenon with mixed consequences.", "category": "写作"},
    {"word": "philosophy", "meaning": "n. 哲学；人生观；宗旨；观点", "example": "Every educational system reflects a specific philosophy of learning.", "category": "写作"},
    {"word": "physical", "meaning": "adj./n. 身体的；物理的；物质的；体检", "example": "Physical activity enhances cognitive performance in students.", "category": "写作"},
    {"word": "pivotal", "meaning": "adj. 关键的；中枢的；枢轴的", "example": "University years can be pivotal in shaping one's career path.", "category": "写作"},
    {"word": "policy", "meaning": "n. 政策；方针；保险单；策略", "example": "Governments formulate policy based on research and public needs.", "category": "写作"},
    {"word": "portray", "meaning": "v. 描绘；描写；扮演；饰演", "example": "Media often portrays scientists in stereotypical ways.", "category": "写作"},
    {"word": "potential", "meaning": "adj./n. 潜在的；可能的；潜力；潜能", "example": "Every child has potential that can be developed through education.", "category": "写作"},
    {"word": "practical", "meaning": "adj. 实际的；实践的；实用的；明智的", "example": "Practical skills complement theoretical knowledge in the workplace.", "category": "写作"},
    {"word": "precise", "meaning": "adj. 精确的；准确的；精密的；恰好的", "example": "Precise language is essential in academic and professional writing.", "category": "写作"},
    {"word": "predict", "meaning": "v. 预言；预测；预报；预示", "example": "Economists predict significant growth in renewable energy sectors.", "category": "写作"},
    {"word": "predominant", "meaning": "adj. 主要的；占优势的；卓越的", "example": "English has become the predominant language of international communication.", "category": "写作"},
    {"word": "prefer", "meaning": "v. 更喜欢；宁愿；提出（控告）", "example": "Most students prefer interactive learning over passive listening.", "category": "写作"},
    {"word": "premise", "meaning": "n./v. 前提；假设；房屋；作出前提", "example": "The argument is based on the premise that all learners are equal.", "category": "写作"},
    {"word": "prepare", "meaning": "v. 准备；预备；筹备；配制", "example": "Universities prepare students for both careers and citizenship.", "category": "写作"},
    {"word": "prescribe", "meaning": "v. 开处方；规定；指定；命令", "example": "Doctors prescribe medication and lifestyle changes for various conditions.", "category": "写作"},
    {"word": "present", "meaning": "adj./v./n. 现在的；出席的；呈现；提交；现在", "example": "Students present their findings in seminars and conferences.", "category": "写作"},
    {"word": "preserve", "meaning": "v./n. 保护；保持；保存；蜜饯；保护区", "example": "Educational institutions preserve and transmit cultural heritage.", "category": "写作"},
    {"word": "primary", "meaning": "adj. 主要的；初级的；基本的；最初的", "example": "The primary purpose of education is to develop critical thinking.", "category": "写作"},
    {"word": "principle", "meaning": "n. 原则；原理；准则；道义", "example": "Ethical principles guide professional conduct in research.", "category": "写作"},
    {"word": "priority", "meaning": "n. 优先；优先权；优先考虑的事", "example": "Reducing dropout rates should be a priority for educational institutions.", "category": "写作"},
    {"word": "proceed", "meaning": "v. 进行；继续下去；开始；起诉", "example": "Students should proceed through the course materials systematically.", "category": "写作"},
    {"word": "process", "meaning": "n./v. 过程；程序；步骤；加工；处理", "example": "Learning is a process that requires active engagement over time.", "category": "写作"},
    {"word": "procure", "meaning": "v. 获得；取得；实现；促成", "example": "Libraries procure resources to support independent research.", "category": "写作"},
    {"word": "produce", "meaning": "v./n. 生产；产生；制作；出版；农产品", "example": "Universities produce research that drives innovation and progress.", "category": "写作"},
    {"word": "professional", "meaning": "adj./n. 专业的；职业的；专业人员；专家", "example": "Professional development helps teachers improve their practice.", "category": "写作"},
    {"word": "proficient", "meaning": "adj. 熟练的；精通的；擅长的", "example": "Becoming proficient in a language requires years of dedicated practice.", "category": "写作"},
    {"word": "profile", "meaning": "n./v. 侧面；轮廓；形象；简介；描述...轮廓", "example": "The institution has maintained a high academic profile internationally.", "category": "写作"},
    {"word": "profound", "meaning": "adj. 深刻的；深远的；渊博的；深邃的", "example": "Education has a profound impact on individual life trajectories.", "category": "写作"},
    {"word": "progress", "meaning": "n./v. 进步；进展；前进；发展", "example": "Students should track their own progress to identify areas for improvement.", "category": "写作"},
    {"word": "project", "meaning": "n./v. 项目；工程；计划；投射；规划；突出", "example": "The research project investigates methods for improving literacy.", "category": "写作"},
    {"word": "promote", "meaning": "v. 促进；提升；推销；发扬", "example": "Schools promote values such as respect, responsibility, and integrity.", "category": "写作"},
    {"word": "prompt", "meaning": "adj./v./n. 迅速的；敏捷的；立即的；促进；提示", "example": "Teachers should provide prompt feedback on student assignments.", "category": "写作"},
    {"word": "prone", "meaning": "adj. 有...倾向的；易于...的；俯卧的", "example": "Students under stress are prone to making careless errors.", "category": "写作"},
    {"word": "proper", "meaning": "adj. 适当的；恰当的；得体的；本身的", "example": "Proper citation practices prevent plagiarism in academic writing.", "category": "写作"},
    {"word": "proportion", "meaning": "n./v. 比例；均衡；部分；使成比例", "example": "A small proportion of students achieve the highest grades.", "category": "写作"},
    {"word": "propose", "meaning": "v. 提议；建议；打算；求婚", "example": "The paper proposes several strategies for improving academic outcomes.", "category": "写作"},
    {"word": "prospective", "meaning": "adj. 预期的；未来的；可能的；有望的", "example": "Prospective international students face many practical challenges.", "category": "写作"},
    {"word": "protocol", "meaning": "n. 协议；议定书；草案；礼仪", "example": "Researchers must follow established ethical protocols.", "category": "写作"},
    {"word": "provide", "meaning": "v. 提供；供应；规定；装备", "example": "Education provides individuals with opportunities for personal growth.", "category": "写作"},
    {"word": "provision", "meaning": "n. 规定；条款；准备；供应品", "example": "The provision of scholarships enables access to higher education.", "category": "写作"},
    {"word": "psychological", "meaning": "adj. 心理的；心理学的；精神上的", "example": "Psychological factors influence motivation and learning outcomes.", "category": "写作"},
    {"word": "pursue", "meaning": "v. 追求；追赶；继续；从事", "example": "Many students pursue postgraduate studies to advance their careers.", "category": "写作"},
    {"word": "qualitative", "meaning": "adj. 定性的；质的；性质的", "example": "Qualitative research explores subjective experiences and perspectives.", "category": "写作"},
    {"word": "quantify", "meaning": "v. 量化；定量；确定数量", "example": "It is difficult to quantify the long-term benefits of education.", "category": "写作"},
    {"word": "query", "meaning": "n./v. 查询；疑问；质问；询问", "example": "Students should query assumptions rather than accept them passively.", "category": "写作"},
    {"word": "question", "meaning": "n./v. 问题；疑问；难题；询问；怀疑", "example": "Researchers question conventional wisdom through critical inquiry.", "category": "写作"},

    # 口语 Speaking (50)
    {"word": "random", "meaning": "adj./n. 随机的；任意的；随便的；随意", "example": "Choosing vocabulary at random is less effective than studying in context.", "category": "口语"},
    {"word": "range", "meaning": "n./v. 范围；幅度；山脉；种类；在...范围内变化", "example": "Students' language abilities range from beginner to advanced.", "category": "口语"},
    {"word": "rational", "meaning": "adj. 合理的；理性的；理智的", "example": "Rational decision-making requires considering evidence carefully.", "category": "口语"},
    {"word": "react", "meaning": "v. 反应；作出反应；反抗；影响", "example": "People react differently to stressful situations like examinations.", "category": "口语"},
    {"word": "readily", "meaning": "adv. 容易地；乐意地；无困难地", "example": "Information is now readily available through digital platforms.", "category": "口语"},
    {"word": "reality", "meaning": "n. 现实；真实；实际存在的事物", "example": "The reality is that learning requires sustained effort over time.", "category": "口语"},
    {"word": "realm", "meaning": "n. 领域；范围；王国；国土", "example": "Artificial intelligence is advancing into new realms of application.", "category": "口语"},
    {"word": "reason", "meaning": "n./v. 理由；原因；理性；推理；说服", "example": "There are many reasons why people choose to study abroad.", "category": "口语"},
    {"word": "recall", "meaning": "v./n. 回忆；回想；召回；取消；记忆力", "example": "Learners can recall information better after spaced repetition.", "category": "口语"},
    {"word": "recent", "meaning": "adj. 最近的；近代的；近来的", "example": "Recent developments in technology have transformed education.", "category": "口语"},
    {"word": "recipe", "meaning": "n. 食谱；配方；秘诀；方法", "example": "Hard work and focus are a reliable recipe for academic success.", "category": "口语"},
    {"word": "recognize", "meaning": "v. 承认；认出；识别；认可；表彰", "example": "Teachers should recognize and encourage individual student strengths.", "category": "口语"},
    {"word": "recommend", "meaning": "v. 推荐；介绍；劝告；使受欢迎", "example": "Experts recommend daily practice for improving language skills.", "category": "口语"},
    {"word": "reconcile", "meaning": "v. 使和解；调和；使一致；使顺从", "example": "It is challenging to reconcile work demands with family life.", "category": "口语"},
    {"word": "record", "meaning": "v./n. 记录；记载；唱片；档案；经历", "example": "Students can record lectures to review content at their own pace.", "category": "口语"},
    {"word": "recover", "meaning": "v. 恢复；痊愈；复原；重新获得", "example": "Students need time to recover from intense examination periods.", "category": "口语"},
    {"word": "recruit", "meaning": "v./n. 招募；招聘；吸收新成员；新兵；新成员", "example": "Universities actively recruit international students each year.", "category": "口语"},
    {"word": "reduce", "meaning": "v. 减少；降低；缩小；归纳为", "example": "Universities should reduce barriers for disadvantaged students.", "category": "口语"},
    {"word": "refer", "meaning": "v. 提到；谈到；参考；查阅；有关；涉及", "example": "Scholars often refer to foundational theories in their research.", "category": "口语"},
    {"word": "reflect", "meaning": "v. 反射；反映；反省；深思熟虑", "example": "Students should reflect on feedback to improve their writing.", "category": "口语"},
    {"word": "reform", "meaning": "n./v. 改革；改良；改造；改过自新", "example": "Educational reform aims to improve outcomes for all learners.", "category": "口语"},
    {"word": "regard", "meaning": "v./n. 认为；把...看作；尊敬；尊重；关心；致意", "example": "People regard education as fundamental to personal success.", "category": "口语"},
    {"word": "regime", "meaning": "n. 政权；政体；制度；统治方式", "example": "Different political regimes prioritize education differently.", "category": "口语"},
